from .thermo_gui_design import Ui_ThermoGUI_main_window
from .create_dataset_gui import Ui_CreateDataset_main_window
from .webcam_dialog_design import Ui_WebCam
from .image_saving_gui import Ui_Save_images_dialog