# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'thermography_gui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ThermoGUI_main_window(object):
    def setupUi(self, ThermoGUI_main_window):
        ThermoGUI_main_window.setObjectName("ThermoGUI_main_window")
        ThermoGUI_main_window.resize(920, 598)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ThermoGUI_main_window.sizePolicy().hasHeightForWidth())
        ThermoGUI_main_window.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ThermoGUI_main_window.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(ThermoGUI_main_window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.left_panel = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.left_panel.sizePolicy().hasHeightForWidth())
        self.left_panel.setSizePolicy(sizePolicy)
        self.left_panel.setObjectName("left_panel")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.left_panel)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.class_image_view = QtWidgets.QLabel(self.left_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.class_image_view.sizePolicy().hasHeightForWidth())
        self.class_image_view.setSizePolicy(sizePolicy)
        self.class_image_view.setMinimumSize(QtCore.QSize(300, 300))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.class_image_view.setFont(font)
        self.class_image_view.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.class_image_view.setMouseTracking(True)
        self.class_image_view.setAutoFillBackground(True)
        self.class_image_view.setFrameShape(QtWidgets.QFrame.Box)
        self.class_image_view.setTextFormat(QtCore.Qt.RichText)
        self.class_image_view.setObjectName("class_image_view")
        self.verticalLayout_11.addWidget(self.class_image_view)
        self.global_progress_bar = QtWidgets.QProgressBar(self.left_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.global_progress_bar.sizePolicy().hasHeightForWidth())
        self.global_progress_bar.setSizePolicy(sizePolicy)
        self.global_progress_bar.setMinimumSize(QtCore.QSize(0, 10))
        self.global_progress_bar.setMaximumSize(QtCore.QSize(16777215, 10))
        self.global_progress_bar.setProperty("value", 0)
        self.global_progress_bar.setTextVisible(False)
        self.global_progress_bar.setInvertedAppearance(False)
        self.global_progress_bar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.global_progress_bar.setObjectName("global_progress_bar")
        self.verticalLayout_11.addWidget(self.global_progress_bar)
        spacerItem = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem)
        self.horizontalLayout_2.addWidget(self.left_panel)
        self.central_panel = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.central_panel.sizePolicy().hasHeightForWidth())
        self.central_panel.setSizePolicy(sizePolicy)
        self.central_panel.setObjectName("central_panel")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.central_panel)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.widget_2 = QtWidgets.QWidget(self.central_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.play_stop_panel = QtWidgets.QVBoxLayout()
        self.play_stop_panel.setContentsMargins(-1, 0, -1, 0)
        self.play_stop_panel.setObjectName("play_stop_panel")
        self.play_stop_buttons_panel = QtWidgets.QHBoxLayout()
        self.play_stop_buttons_panel.setContentsMargins(-1, 0, -1, 0)
        self.play_stop_buttons_panel.setObjectName("play_stop_buttons_panel")
        self.play_video_button = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.play_video_button.sizePolicy().hasHeightForWidth())
        self.play_video_button.setSizePolicy(sizePolicy)
        self.play_video_button.setMinimumSize(QtCore.QSize(20, 0))
        self.play_video_button.setCheckable(False)
        self.play_video_button.setObjectName("play_video_button")
        self.play_stop_buttons_panel.addWidget(self.play_video_button)
        self.pause_video_button = QtWidgets.QPushButton(self.widget_2)
        self.pause_video_button.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pause_video_button.sizePolicy().hasHeightForWidth())
        self.pause_video_button.setSizePolicy(sizePolicy)
        self.pause_video_button.setMinimumSize(QtCore.QSize(20, 0))
        self.pause_video_button.setCheckable(False)
        self.pause_video_button.setObjectName("pause_video_button")
        self.play_stop_buttons_panel.addWidget(self.pause_video_button)
        self.stop_video_button = QtWidgets.QPushButton(self.widget_2)
        self.stop_video_button.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stop_video_button.sizePolicy().hasHeightForWidth())
        self.stop_video_button.setSizePolicy(sizePolicy)
        self.stop_video_button.setMinimumSize(QtCore.QSize(20, 0))
        self.stop_video_button.setCheckable(False)
        self.stop_video_button.setChecked(False)
        self.stop_video_button.setObjectName("stop_video_button")
        self.play_stop_buttons_panel.addWidget(self.stop_video_button)
        self.play_stop_panel.addLayout(self.play_stop_buttons_panel)
        self.reset_button = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reset_button.sizePolicy().hasHeightForWidth())
        self.reset_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.reset_button.setFont(font)
        self.reset_button.setAutoFillBackground(False)
        self.reset_button.setAutoDefault(False)
        self.reset_button.setDefault(False)
        self.reset_button.setFlat(False)
        self.reset_button.setObjectName("reset_button")
        self.play_stop_panel.addWidget(self.reset_button)
        self.verticalLayout_6.addLayout(self.play_stop_panel)
        self.tabWidget = QtWidgets.QTabWidget(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.input_image_tab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_image_tab.sizePolicy().hasHeightForWidth())
        self.input_image_tab.setSizePolicy(sizePolicy)
        self.input_image_tab.setObjectName("input_image_tab")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.input_image_tab)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.video_view = QtWidgets.QLabel(self.input_image_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.video_view.sizePolicy().hasHeightForWidth())
        self.video_view.setSizePolicy(sizePolicy)
        self.video_view.setMinimumSize(QtCore.QSize(250, 150))
        self.video_view.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.video_view.setFont(font)
        self.video_view.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.video_view.setMouseTracking(True)
        self.video_view.setAutoFillBackground(True)
        self.video_view.setFrameShape(QtWidgets.QFrame.Box)
        self.video_view.setFrameShadow(QtWidgets.QFrame.Plain)
        self.video_view.setTextFormat(QtCore.Qt.RichText)
        self.video_view.setScaledContents(False)
        self.video_view.setAlignment(QtCore.Qt.AlignCenter)
        self.video_view.setWordWrap(False)
        self.video_view.setObjectName("video_view")
        self.horizontalLayout.addWidget(self.video_view)
        self.tabWidget.addTab(self.input_image_tab, "")
        self.canny_edges_tab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.canny_edges_tab.sizePolicy().hasHeightForWidth())
        self.canny_edges_tab.setSizePolicy(sizePolicy)
        self.canny_edges_tab.setObjectName("canny_edges_tab")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.canny_edges_tab)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.canny_edges_view = QtWidgets.QLabel(self.canny_edges_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.canny_edges_view.sizePolicy().hasHeightForWidth())
        self.canny_edges_view.setSizePolicy(sizePolicy)
        self.canny_edges_view.setMinimumSize(QtCore.QSize(250, 150))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.canny_edges_view.setFont(font)
        self.canny_edges_view.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.canny_edges_view.setAutoFillBackground(True)
        self.canny_edges_view.setFrameShape(QtWidgets.QFrame.Box)
        self.canny_edges_view.setTextFormat(QtCore.Qt.RichText)
        self.canny_edges_view.setScaledContents(False)
        self.canny_edges_view.setAlignment(QtCore.Qt.AlignCenter)
        self.canny_edges_view.setObjectName("canny_edges_view")
        self.horizontalLayout_3.addWidget(self.canny_edges_view)
        self.tabWidget.addTab(self.canny_edges_tab, "")
        self.segment_image_tab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.segment_image_tab.sizePolicy().hasHeightForWidth())
        self.segment_image_tab.setSizePolicy(sizePolicy)
        self.segment_image_tab.setObjectName("segment_image_tab")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.segment_image_tab)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.segment_image_view = QtWidgets.QLabel(self.segment_image_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.segment_image_view.sizePolicy().hasHeightForWidth())
        self.segment_image_view.setSizePolicy(sizePolicy)
        self.segment_image_view.setMinimumSize(QtCore.QSize(250, 150))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.segment_image_view.setFont(font)
        self.segment_image_view.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.segment_image_view.setAutoFillBackground(True)
        self.segment_image_view.setFrameShape(QtWidgets.QFrame.Box)
        self.segment_image_view.setTextFormat(QtCore.Qt.RichText)
        self.segment_image_view.setScaledContents(False)
        self.segment_image_view.setObjectName("segment_image_view")
        self.horizontalLayout_5.addWidget(self.segment_image_view)
        self.tabWidget.addTab(self.segment_image_tab, "")
        self.rectangle_image_tab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rectangle_image_tab.sizePolicy().hasHeightForWidth())
        self.rectangle_image_tab.setSizePolicy(sizePolicy)
        self.rectangle_image_tab.setObjectName("rectangle_image_tab")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.rectangle_image_tab)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.rectangle_image_view = QtWidgets.QLabel(self.rectangle_image_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rectangle_image_view.sizePolicy().hasHeightForWidth())
        self.rectangle_image_view.setSizePolicy(sizePolicy)
        self.rectangle_image_view.setMinimumSize(QtCore.QSize(250, 150))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.rectangle_image_view.setFont(font)
        self.rectangle_image_view.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.rectangle_image_view.setMouseTracking(True)
        self.rectangle_image_view.setAutoFillBackground(True)
        self.rectangle_image_view.setFrameShape(QtWidgets.QFrame.Box)
        self.rectangle_image_view.setTextFormat(QtCore.Qt.RichText)
        self.rectangle_image_view.setScaledContents(False)
        self.rectangle_image_view.setObjectName("rectangle_image_view")
        self.horizontalLayout_4.addWidget(self.rectangle_image_view)
        self.tabWidget.addTab(self.rectangle_image_tab, "")
        self.verticalLayout_6.addWidget(self.tabWidget)
        self.line_6 = QtWidgets.QFrame(self.widget_2)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_6.addWidget(self.line_6)
        self.widget_4 = QtWidgets.QWidget(self.widget_2)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.module_image_view = QtWidgets.QLabel(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.module_image_view.sizePolicy().hasHeightForWidth())
        self.module_image_view.setSizePolicy(sizePolicy)
        self.module_image_view.setMinimumSize(QtCore.QSize(250, 150))
        self.module_image_view.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.module_image_view.setFont(font)
        self.module_image_view.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.module_image_view.setAutoFillBackground(True)
        self.module_image_view.setFrameShape(QtWidgets.QFrame.Box)
        self.module_image_view.setTextFormat(QtCore.Qt.RichText)
        self.module_image_view.setScaledContents(False)
        self.module_image_view.setObjectName("module_image_view")
        self.horizontalLayout_7.addWidget(self.module_image_view)
        self.verticalLayout_6.addWidget(self.widget_4)
        self.verticalLayout_10.addWidget(self.widget_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem1)
        self.horizontalLayout_2.addWidget(self.central_panel)
        self.control_panel = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.control_panel.sizePolicy().hasHeightForWidth())
        self.control_panel.setSizePolicy(sizePolicy)
        self.control_panel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.control_panel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.control_panel.setObjectName("control_panel")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.control_panel)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tab_widget = QtWidgets.QTabWidget(self.control_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_widget.sizePolicy().hasHeightForWidth())
        self.tab_widget.setSizePolicy(sizePolicy)
        self.tab_widget.setAcceptDrops(False)
        self.tab_widget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tab_widget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tab_widget.setIconSize(QtCore.QSize(16, 16))
        self.tab_widget.setElideMode(QtCore.Qt.ElideNone)
        self.tab_widget.setUsesScrollButtons(True)
        self.tab_widget.setDocumentMode(False)
        self.tab_widget.setTabsClosable(False)
        self.tab_widget.setMovable(False)
        self.tab_widget.setTabBarAutoHide(False)
        self.tab_widget.setObjectName("tab_widget")
        self.video_tab = QtWidgets.QWidget()
        self.video_tab.setObjectName("video_tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.video_tab)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(10, 10, 10, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.video_tab)
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.video_index_panel = QtWidgets.QGridLayout()
        self.video_index_panel.setContentsMargins(-1, 2, -1, 2)
        self.video_index_panel.setObjectName("video_index_panel")
        self.video_from_index = QtWidgets.QSpinBox(self.video_tab)
        self.video_from_index.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.video_from_index.setMaximum(100000)
        self.video_from_index.setObjectName("video_from_index")
        self.video_index_panel.addWidget(self.video_from_index, 1, 0, 1, 1)
        self.from_video_index_label = QtWidgets.QLabel(self.video_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.from_video_index_label.sizePolicy().hasHeightForWidth())
        self.from_video_index_label.setSizePolicy(sizePolicy)
        self.from_video_index_label.setObjectName("from_video_index_label")
        self.video_index_panel.addWidget(self.from_video_index_label, 0, 0, 1, 1)
        self.to_video_index_label = QtWidgets.QLabel(self.video_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.to_video_index_label.sizePolicy().hasHeightForWidth())
        self.to_video_index_label.setSizePolicy(sizePolicy)
        self.to_video_index_label.setObjectName("to_video_index_label")
        self.video_index_panel.addWidget(self.to_video_index_label, 0, 1, 1, 1)
        self.video_to_index = QtWidgets.QSpinBox(self.video_tab)
        self.video_to_index.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.video_to_index.setAutoFillBackground(False)
        self.video_to_index.setMinimum(0)
        self.video_to_index.setMaximum(100000)
        self.video_to_index.setProperty("value", 500)
        self.video_to_index.setObjectName("video_to_index")
        self.video_index_panel.addWidget(self.video_to_index, 1, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.video_index_panel)
        self.load_video_button = QtWidgets.QPushButton(self.video_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.load_video_button.sizePolicy().hasHeightForWidth())
        self.load_video_button.setSizePolicy(sizePolicy)
        self.load_video_button.setCheckable(False)
        self.load_video_button.setDefault(True)
        self.load_video_button.setFlat(False)
        self.load_video_button.setObjectName("load_video_button")
        self.verticalLayout_3.addWidget(self.load_video_button)
        self.line = QtWidgets.QFrame(self.video_tab)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.label_2 = QtWidgets.QLabel(self.video_tab)
        self.label_2.setTextFormat(QtCore.Qt.RichText)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.detect_webcam_button = QtWidgets.QPushButton(self.video_tab)
        self.detect_webcam_button.setObjectName("detect_webcam_button")
        self.verticalLayout_3.addWidget(self.detect_webcam_button)
        self.line_5 = QtWidgets.QFrame(self.video_tab)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_3.addWidget(self.line_5)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.image_scaling_label = QtWidgets.QLabel(self.video_tab)
        self.image_scaling_label.setObjectName("image_scaling_label")
        self.verticalLayout_4.addWidget(self.image_scaling_label)
        self.image_scaling_slider = QtWidgets.QSlider(self.video_tab)
        self.image_scaling_slider.setMinimum(1)
        self.image_scaling_slider.setMaximum(19)
        self.image_scaling_slider.setSingleStep(0)
        self.image_scaling_slider.setPageStep(1)
        self.image_scaling_slider.setProperty("value", 10)
        self.image_scaling_slider.setSliderPosition(10)
        self.image_scaling_slider.setTracking(True)
        self.image_scaling_slider.setOrientation(QtCore.Qt.Horizontal)
        self.image_scaling_slider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.image_scaling_slider.setTickInterval(2)
        self.image_scaling_slider.setObjectName("image_scaling_slider")
        self.verticalLayout_4.addWidget(self.image_scaling_slider)
        self.verticalLayout_3.addLayout(self.verticalLayout_4)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.tab_widget.addTab(self.video_tab, "")
        self.preprocessing_tab = QtWidgets.QWidget()
        self.preprocessing_tab.setObjectName("preprocessing_tab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.preprocessing_tab)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setContentsMargins(10, 10, 10, -1)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.preprocessing_label = QtWidgets.QLabel(self.preprocessing_tab)
        self.preprocessing_label.setTextFormat(QtCore.Qt.RichText)
        self.preprocessing_label.setObjectName("preprocessing_label")
        self.verticalLayout_9.addWidget(self.preprocessing_label)
        self.preprocessing_layout = QtWidgets.QVBoxLayout()
        self.preprocessing_layout.setContentsMargins(-1, 0, -1, -1)
        self.preprocessing_layout.setObjectName("preprocessing_layout")
        self.undistort_image_box = QtWidgets.QCheckBox(self.preprocessing_tab)
        self.undistort_image_box.setChecked(True)
        self.undistort_image_box.setTristate(False)
        self.undistort_image_box.setObjectName("undistort_image_box")
        self.preprocessing_layout.addWidget(self.undistort_image_box)
        self.preprocessing_grid_layout = QtWidgets.QGridLayout()
        self.preprocessing_grid_layout.setContentsMargins(-1, 10, -1, -1)
        self.preprocessing_grid_layout.setObjectName("preprocessing_grid_layout")
        self.angle_label = QtWidgets.QLabel(self.preprocessing_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.angle_label.sizePolicy().hasHeightForWidth())
        self.angle_label.setSizePolicy(sizePolicy)
        self.angle_label.setObjectName("angle_label")
        self.preprocessing_grid_layout.addWidget(self.angle_label, 0, 0, 1, 1)
        self.angle_value = QtWidgets.QSpinBox(self.preprocessing_tab)
        self.angle_value.setMinimum(0)
        self.angle_value.setMaximum(360)
        self.angle_value.setSingleStep(10)
        self.angle_value.setObjectName("angle_value")
        self.preprocessing_grid_layout.addWidget(self.angle_value, 0, 1, 1, 1)
        self.blur_label = QtWidgets.QLabel(self.preprocessing_tab)
        self.blur_label.setObjectName("blur_label")
        self.preprocessing_grid_layout.addWidget(self.blur_label, 1, 0, 1, 1)
        self.blur_value = QtWidgets.QSpinBox(self.preprocessing_tab)
        self.blur_value.setMaximum(15)
        self.blur_value.setProperty("value", 3)
        self.blur_value.setObjectName("blur_value")
        self.preprocessing_grid_layout.addWidget(self.blur_value, 1, 1, 1, 1)
        self.preprocessing_layout.addLayout(self.preprocessing_grid_layout)
        self.verticalLayout_9.addLayout(self.preprocessing_layout)
        self.line_2 = QtWidgets.QFrame(self.preprocessing_tab)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_9.addWidget(self.line_2)
        self.canny_parameters_label = QtWidgets.QLabel(self.preprocessing_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.canny_parameters_label.sizePolicy().hasHeightForWidth())
        self.canny_parameters_label.setSizePolicy(sizePolicy)
        self.canny_parameters_label.setTextFormat(QtCore.Qt.RichText)
        self.canny_parameters_label.setObjectName("canny_parameters_label")
        self.verticalLayout_9.addWidget(self.canny_parameters_label)
        self.histeresis_label = QtWidgets.QLabel(self.preprocessing_tab)
        self.histeresis_label.setTextFormat(QtCore.Qt.RichText)
        self.histeresis_label.setObjectName("histeresis_label")
        self.verticalLayout_9.addWidget(self.histeresis_label)
        self.histeresis_grid_layout = QtWidgets.QGridLayout()
        self.histeresis_grid_layout.setContentsMargins(-1, 0, -1, -1)
        self.histeresis_grid_layout.setObjectName("histeresis_grid_layout")
        self.min_histeresis_value = QtWidgets.QSpinBox(self.preprocessing_tab)
        self.min_histeresis_value.setWrapping(False)
        self.min_histeresis_value.setFrame(True)
        self.min_histeresis_value.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.min_histeresis_value.setMaximum(500)
        self.min_histeresis_value.setSingleStep(10)
        self.min_histeresis_value.setProperty("value", 30)
        self.min_histeresis_value.setObjectName("min_histeresis_value")
        self.histeresis_grid_layout.addWidget(self.min_histeresis_value, 1, 0, 1, 1)
        self.label_max_histeresis = QtWidgets.QLabel(self.preprocessing_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_max_histeresis.sizePolicy().hasHeightForWidth())
        self.label_max_histeresis.setSizePolicy(sizePolicy)
        self.label_max_histeresis.setMaximumSize(QtCore.QSize(16777215, 16))
        self.label_max_histeresis.setObjectName("label_max_histeresis")
        self.histeresis_grid_layout.addWidget(self.label_max_histeresis, 0, 1, 1, 1)
        self.max_histeresis_value = QtWidgets.QSpinBox(self.preprocessing_tab)
        self.max_histeresis_value.setMaximum(500)
        self.max_histeresis_value.setSingleStep(10)
        self.max_histeresis_value.setProperty("value", 140)
        self.max_histeresis_value.setObjectName("max_histeresis_value")
        self.histeresis_grid_layout.addWidget(self.max_histeresis_value, 1, 1, 1, 1)
        self.label_min_histeresis = QtWidgets.QLabel(self.preprocessing_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_min_histeresis.sizePolicy().hasHeightForWidth())
        self.label_min_histeresis.setSizePolicy(sizePolicy)
        self.label_min_histeresis.setMaximumSize(QtCore.QSize(16777215, 16))
        self.label_min_histeresis.setObjectName("label_min_histeresis")
        self.histeresis_grid_layout.addWidget(self.label_min_histeresis, 0, 0, 1, 1)
        self.verticalLayout_9.addLayout(self.histeresis_grid_layout)
        self.dilation_layout = QtWidgets.QHBoxLayout()
        self.dilation_layout.setContentsMargins(-1, 0, -1, -1)
        self.dilation_layout.setObjectName("dilation_layout")
        self.dilation_label = QtWidgets.QLabel(self.preprocessing_tab)
        self.dilation_label.setObjectName("dilation_label")
        self.dilation_layout.addWidget(self.dilation_label)
        self.dilation_value = QtWidgets.QSpinBox(self.preprocessing_tab)
        self.dilation_value.setMaximum(10)
        self.dilation_value.setProperty("value", 3)
        self.dilation_value.setObjectName("dilation_value")
        self.dilation_layout.addWidget(self.dilation_value)
        self.verticalLayout_9.addLayout(self.dilation_layout)
        self.verticalLayout_5.addLayout(self.verticalLayout_9)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem3)
        self.tab_widget.addTab(self.preprocessing_tab, "")
        self.segment_tab = QtWidgets.QWidget()
        self.segment_tab.setObjectName("segment_tab")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.segment_tab)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setContentsMargins(10, 10, 10, -1)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.segment_label = QtWidgets.QLabel(self.segment_tab)
        self.segment_label.setTextFormat(QtCore.Qt.RichText)
        self.segment_label.setObjectName("segment_label")
        self.verticalLayout_12.addWidget(self.segment_label)
        self.detection_layout = QtWidgets.QGridLayout()
        self.detection_layout.setContentsMargins(-1, 0, -1, -1)
        self.detection_layout.setObjectName("detection_layout")
        self.max_gap_value = QtWidgets.QSpinBox(self.segment_tab)
        self.max_gap_value.setMaximum(500)
        self.max_gap_value.setSingleStep(10)
        self.max_gap_value.setProperty("value", 150)
        self.max_gap_value.setObjectName("max_gap_value")
        self.detection_layout.addWidget(self.max_gap_value, 4, 1, 1, 1)
        self.max_gap_label = QtWidgets.QLabel(self.segment_tab)
        self.max_gap_label.setObjectName("max_gap_label")
        self.detection_layout.addWidget(self.max_gap_label, 4, 0, 1, 1)
        self.min_length_value = QtWidgets.QSpinBox(self.segment_tab)
        self.min_length_value.setMinimum(0)
        self.min_length_value.setMaximum(500)
        self.min_length_value.setSingleStep(10)
        self.min_length_value.setProperty("value", 50)
        self.min_length_value.setObjectName("min_length_value")
        self.detection_layout.addWidget(self.min_length_value, 3, 1, 1, 1)
        self.delta_rho_label = QtWidgets.QLabel(self.segment_tab)
        self.delta_rho_label.setObjectName("delta_rho_label")
        self.detection_layout.addWidget(self.delta_rho_label, 0, 0, 1, 1)
        self.min_votes_value = QtWidgets.QSpinBox(self.segment_tab)
        self.min_votes_value.setMinimum(0)
        self.min_votes_value.setMaximum(500)
        self.min_votes_value.setSingleStep(10)
        self.min_votes_value.setProperty("value", 60)
        self.min_votes_value.setObjectName("min_votes_value")
        self.detection_layout.addWidget(self.min_votes_value, 2, 1, 1, 1)
        self.delta_theta_value = QtWidgets.QSpinBox(self.segment_tab)
        self.delta_theta_value.setMinimum(1)
        self.delta_theta_value.setMaximum(180)
        self.delta_theta_value.setProperty("value", 1)
        self.delta_theta_value.setObjectName("delta_theta_value")
        self.detection_layout.addWidget(self.delta_theta_value, 1, 1, 1, 1)
        self.min_votes_label = QtWidgets.QLabel(self.segment_tab)
        self.min_votes_label.setObjectName("min_votes_label")
        self.detection_layout.addWidget(self.min_votes_label, 2, 0, 1, 1)
        self.delta_rho_value = QtWidgets.QSpinBox(self.segment_tab)
        self.delta_rho_value.setMinimum(1)
        self.delta_rho_value.setMaximum(100)
        self.delta_rho_value.setProperty("value", 1)
        self.delta_rho_value.setObjectName("delta_rho_value")
        self.detection_layout.addWidget(self.delta_rho_value, 0, 1, 1, 1)
        self.min_length_label = QtWidgets.QLabel(self.segment_tab)
        self.min_length_label.setObjectName("min_length_label")
        self.detection_layout.addWidget(self.min_length_label, 3, 0, 1, 1)
        self.delta_theta_label = QtWidgets.QLabel(self.segment_tab)
        self.delta_theta_label.setObjectName("delta_theta_label")
        self.detection_layout.addWidget(self.delta_theta_label, 1, 0, 1, 1)
        self.extend_segments_label = QtWidgets.QLabel(self.segment_tab)
        self.extend_segments_label.setObjectName("extend_segments_label")
        self.detection_layout.addWidget(self.extend_segments_label, 5, 0, 1, 1)
        self.extend_segments_value = QtWidgets.QSpinBox(self.segment_tab)
        self.extend_segments_value.setMaximum(500)
        self.extend_segments_value.setProperty("value", 10)
        self.extend_segments_value.setObjectName("extend_segments_value")
        self.detection_layout.addWidget(self.extend_segments_value, 5, 1, 1, 1)
        self.verticalLayout_12.addLayout(self.detection_layout)
        self.line_3 = QtWidgets.QFrame(self.segment_tab)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_12.addWidget(self.line_3)
        self.clustering_label = QtWidgets.QLabel(self.segment_tab)
        self.clustering_label.setTextFormat(QtCore.Qt.RichText)
        self.clustering_label.setObjectName("clustering_label")
        self.verticalLayout_12.addWidget(self.clustering_label)
        self.clustering_layout = QtWidgets.QGridLayout()
        self.clustering_layout.setContentsMargins(-1, 0, -1, -1)
        self.clustering_layout.setObjectName("clustering_layout")
        self.num_init_label = QtWidgets.QLabel(self.segment_tab)
        self.num_init_label.setObjectName("num_init_label")
        self.clustering_layout.addWidget(self.num_init_label, 2, 0, 1, 1)
        self.cluster_type_label = QtWidgets.QLabel(self.segment_tab)
        self.cluster_type_label.setObjectName("cluster_type_label")
        self.clustering_layout.addWidget(self.cluster_type_label, 0, 0, 1, 1)
        self.num_clusters_value = QtWidgets.QSpinBox(self.segment_tab)
        self.num_clusters_value.setMinimum(2)
        self.num_clusters_value.setObjectName("num_clusters_value")
        self.clustering_layout.addWidget(self.num_clusters_value, 1, 1, 1, 1)
        self.num_init_value = QtWidgets.QSpinBox(self.segment_tab)
        self.num_init_value.setEnabled(False)
        self.num_init_value.setMinimum(1)
        self.num_init_value.setProperty("value", 5)
        self.num_init_value.setObjectName("num_init_value")
        self.clustering_layout.addWidget(self.num_init_value, 2, 1, 1, 1)
        self.num_clusters_label = QtWidgets.QLabel(self.segment_tab)
        self.num_clusters_label.setObjectName("num_clusters_label")
        self.clustering_layout.addWidget(self.num_clusters_label, 1, 0, 1, 1)
        self.cluster_type_layout = QtWidgets.QHBoxLayout()
        self.cluster_type_layout.setObjectName("cluster_type_layout")
        self.gmm_value = QtWidgets.QRadioButton(self.segment_tab)
        self.gmm_value.setChecked(True)
        self.gmm_value.setObjectName("gmm_value")
        self.cluster_type_layout.addWidget(self.gmm_value)
        self.knn_value = QtWidgets.QRadioButton(self.segment_tab)
        self.knn_value.setObjectName("knn_value")
        self.cluster_type_layout.addWidget(self.knn_value)
        self.clustering_layout.addLayout(self.cluster_type_layout, 0, 1, 1, 1)
        self.verticalLayout_12.addLayout(self.clustering_layout)
        self.features_label = QtWidgets.QLabel(self.segment_tab)
        self.features_label.setObjectName("features_label")
        self.verticalLayout_12.addWidget(self.features_label)
        self.features_layout = QtWidgets.QHBoxLayout()
        self.features_layout.setContentsMargins(-1, 0, -1, -1)
        self.features_layout.setObjectName("features_layout")
        self.swipe_clusters_value = QtWidgets.QCheckBox(self.segment_tab)
        self.swipe_clusters_value.setObjectName("swipe_clusters_value")
        self.features_layout.addWidget(self.swipe_clusters_value)
        self.use_angle_value = QtWidgets.QCheckBox(self.segment_tab)
        self.use_angle_value.setChecked(True)
        self.use_angle_value.setObjectName("use_angle_value")
        self.features_layout.addWidget(self.use_angle_value)
        self.use_centers_value = QtWidgets.QCheckBox(self.segment_tab)
        self.use_centers_value.setObjectName("use_centers_value")
        self.features_layout.addWidget(self.use_centers_value)
        self.verticalLayout_12.addLayout(self.features_layout)
        self.line_4 = QtWidgets.QFrame(self.segment_tab)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_12.addWidget(self.line_4)
        self.cleaning_label = QtWidgets.QLabel(self.segment_tab)
        self.cleaning_label.setTextFormat(QtCore.Qt.RichText)
        self.cleaning_label.setObjectName("cleaning_label")
        self.verticalLayout_12.addWidget(self.cleaning_label)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.max_merging_distance_label = QtWidgets.QLabel(self.segment_tab)
        self.max_merging_distance_label.setObjectName("max_merging_distance_label")
        self.gridLayout.addWidget(self.max_merging_distance_label, 2, 0, 1, 1)
        self.max_angle_variation_mean_label = QtWidgets.QLabel(self.segment_tab)
        self.max_angle_variation_mean_label.setObjectName("max_angle_variation_mean_label")
        self.gridLayout.addWidget(self.max_angle_variation_mean_label, 0, 0, 1, 1)
        self.max_merging_angle_label = QtWidgets.QLabel(self.segment_tab)
        self.max_merging_angle_label.setObjectName("max_merging_angle_label")
        self.gridLayout.addWidget(self.max_merging_angle_label, 1, 0, 1, 1)
        self.max_angle_variation_mean_value = QtWidgets.QSpinBox(self.segment_tab)
        self.max_angle_variation_mean_value.setMaximum(90)
        self.max_angle_variation_mean_value.setSingleStep(5)
        self.max_angle_variation_mean_value.setProperty("value", 20)
        self.max_angle_variation_mean_value.setObjectName("max_angle_variation_mean_value")
        self.gridLayout.addWidget(self.max_angle_variation_mean_value, 0, 1, 1, 1)
        self.max_merging_angle_value = QtWidgets.QSpinBox(self.segment_tab)
        self.max_merging_angle_value.setMaximum(90)
        self.max_merging_angle_value.setSingleStep(5)
        self.max_merging_angle_value.setProperty("value", 10)
        self.max_merging_angle_value.setObjectName("max_merging_angle_value")
        self.gridLayout.addWidget(self.max_merging_angle_value, 1, 1, 1, 1)
        self.max_merging_distance_value = QtWidgets.QSpinBox(self.segment_tab)
        self.max_merging_distance_value.setMaximum(500)
        self.max_merging_distance_value.setSingleStep(10)
        self.max_merging_distance_value.setProperty("value", 10)
        self.max_merging_distance_value.setObjectName("max_merging_distance_value")
        self.gridLayout.addWidget(self.max_merging_distance_value, 2, 1, 1, 1)
        self.verticalLayout_12.addLayout(self.gridLayout)
        self.verticalLayout_7.addLayout(self.verticalLayout_12)
        spacerItem4 = QtWidgets.QSpacerItem(20, 41, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem4)
        self.tab_widget.addTab(self.segment_tab, "")
        self.module_tab = QtWidgets.QWidget()
        self.module_tab.setObjectName("module_tab")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.module_tab)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setContentsMargins(10, 10, 10, -1)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.filter_label = QtWidgets.QLabel(self.module_tab)
        self.filter_label.setTextFormat(QtCore.Qt.RichText)
        self.filter_label.setObjectName("filter_label")
        self.verticalLayout_13.addWidget(self.filter_label)
        self.module_filter_layout = QtWidgets.QGridLayout()
        self.module_filter_layout.setContentsMargins(-1, 0, -1, -1)
        self.module_filter_layout.setObjectName("module_filter_layout")
        self.ratio_max_deviation_value = QtWidgets.QDoubleSpinBox(self.module_tab)
        self.ratio_max_deviation_value.setMaximum(10.0)
        self.ratio_max_deviation_value.setSingleStep(0.1)
        self.ratio_max_deviation_value.setProperty("value", 0.3)
        self.ratio_max_deviation_value.setObjectName("ratio_max_deviation_value")
        self.module_filter_layout.addWidget(self.ratio_max_deviation_value, 1, 1, 1, 1)
        self.ratio_max_deviation_label = QtWidgets.QLabel(self.module_tab)
        self.ratio_max_deviation_label.setObjectName("ratio_max_deviation_label")
        self.module_filter_layout.addWidget(self.ratio_max_deviation_label, 1, 0, 1, 1)
        self.min_area_value = QtWidgets.QSpinBox(self.module_tab)
        self.min_area_value.setMaximum(1000000)
        self.min_area_value.setSingleStep(100)
        self.min_area_value.setProperty("value", 800)
        self.min_area_value.setObjectName("min_area_value")
        self.module_filter_layout.addWidget(self.min_area_value, 2, 1, 1, 1)
        self.min_area_label = QtWidgets.QLabel(self.module_tab)
        self.min_area_label.setObjectName("min_area_label")
        self.module_filter_layout.addWidget(self.min_area_label, 2, 0, 1, 1)
        self.expected_ratio_label = QtWidgets.QLabel(self.module_tab)
        self.expected_ratio_label.setObjectName("expected_ratio_label")
        self.module_filter_layout.addWidget(self.expected_ratio_label, 0, 0, 1, 1)
        self.expected_ratio_value = QtWidgets.QDoubleSpinBox(self.module_tab)
        self.expected_ratio_value.setMinimum(0.1)
        self.expected_ratio_value.setMaximum(5.0)
        self.expected_ratio_value.setSingleStep(0.1)
        self.expected_ratio_value.setProperty("value", 1.5)
        self.expected_ratio_value.setObjectName("expected_ratio_value")
        self.module_filter_layout.addWidget(self.expected_ratio_value, 0, 1, 1, 1)
        self.verticalLayout_13.addLayout(self.module_filter_layout)
        self.verticalLayout_8.addLayout(self.verticalLayout_13)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem5)
        self.tab_widget.addTab(self.module_tab, "")
        self.verticalLayout_2.addWidget(self.tab_widget)
        spacerItem6 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem6)
        self.horizontalLayout_2.addWidget(self.control_panel, 0, QtCore.Qt.AlignTop)
        ThermoGUI_main_window.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(ThermoGUI_main_window)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 920, 21))
        self.menuBar.setObjectName("menuBar")
        self.FileMenu = QtWidgets.QMenu(self.menuBar)
        self.FileMenu.setObjectName("FileMenu")
        ThermoGUI_main_window.setMenuBar(self.menuBar)
        self.actionLoad = QtWidgets.QAction(ThermoGUI_main_window)
        self.actionLoad.setObjectName("actionLoad")
        self.file_about = QtWidgets.QAction(ThermoGUI_main_window)
        self.file_about.setObjectName("file_about")
        self.file_exit = QtWidgets.QAction(ThermoGUI_main_window)
        self.file_exit.setObjectName("file_exit")
        self.FileMenu.addAction(self.file_about)
        self.FileMenu.addSeparator()
        self.FileMenu.addAction(self.file_exit)
        self.menuBar.addAction(self.FileMenu.menuAction())

        self.retranslateUi(ThermoGUI_main_window)
        self.tabWidget.setCurrentIndex(3)
        self.tab_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ThermoGUI_main_window)

    def retranslateUi(self, ThermoGUI_main_window):
        _translate = QtCore.QCoreApplication.translate
        ThermoGUI_main_window.setWindowTitle(_translate("ThermoGUI_main_window", "ThermoGUI"))
        ThermoGUI_main_window.setWhatsThis(_translate("ThermoGUI_main_window", "<html><head/><body><p>Tool Bar</p><p><br/></p></body></html>"))
        self.class_image_view.setText(_translate("ThermoGUI_main_window", "<html><head/><body><p align=\"center\">Classes Image</p></body></html>"))
        self.global_progress_bar.setFormat(_translate("ThermoGUI_main_window", "%p%"))
        self.play_video_button.setToolTip(_translate("ThermoGUI_main_window", "<html><head/><body><p>Play\n"
"                                                                        the current video/Webcam.</p></body></html>\n"
"                                                                    "))
        self.play_video_button.setText(_translate("ThermoGUI_main_window", "Play"))
        self.pause_video_button.setToolTip(_translate("ThermoGUI_main_window", "<html><head/><body><p>Pause\n"
"                                                                        the current video/Webcam.</p></body></html>\n"
"                                                                    "))
        self.pause_video_button.setText(_translate("ThermoGUI_main_window", "Pause"))
        self.stop_video_button.setToolTip(_translate("ThermoGUI_main_window", "<html><head/><body><p>Resets\n"
"                                                                        the current video to the start.</p></body></html>\n"
"                                                                    "))
        self.stop_video_button.setText(_translate("ThermoGUI_main_window", "Stop"))
        self.reset_button.setToolTip(_translate("ThermoGUI_main_window", "<html><head/><body><p><span\n"
"                                                                style=\" font-weight:400;\">Resets the state\n"
"                                                                of the ThermoGUI.</span></p></body></html>\n"
"                                                            "))
        self.reset_button.setText(_translate("ThermoGUI_main_window", "Reset"))
        self.video_view.setText(_translate("ThermoGUI_main_window", "<html><head/><body><p\n"
"                                                                        align=\"center\">Input Image</p></body></html>\n"
"                                                                    "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.input_image_tab), _translate("ThermoGUI_main_window", "Input image"))
        self.canny_edges_view.setText(_translate("ThermoGUI_main_window", "<html><head/><body><p\n"
"                                                                        align=\"center\">Edges Image</p></body></html>\n"
"                                                                    "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.canny_edges_tab), _translate("ThermoGUI_main_window", "Edges image"))
        self.segment_image_view.setText(_translate("ThermoGUI_main_window", "<html><head/><body><p\n"
"                                                                        align=\"center\">Segment Image</p></body></html>\n"
"                                                                    "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.segment_image_tab), _translate("ThermoGUI_main_window", "Segment image"))
        self.rectangle_image_view.setText(_translate("ThermoGUI_main_window", "<html><head/><body><p\n"
"                                                                        align=\"center\">Rectangle Image</p></body></html>\n"
"                                                                    "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.rectangle_image_tab), _translate("ThermoGUI_main_window", "Rectangle image"))
        self.module_image_view.setText(_translate("ThermoGUI_main_window", "<html><head/><body><p align=\"center\">Module\n"
"                                            Map</p></body></html>\n"
"                                        "))
        self.label.setText(_translate("ThermoGUI_main_window", "<html><head/><body><p\n"
"                                                                    align=\"center\"><span style=\"\n"
"                                                                    font-weight:600;\">File</span></p></body></html>\n"
"                                                                "))
        self.video_from_index.setToolTip(_translate("ThermoGUI_main_window", "<html><head/><body><p>Initial\n"
"                                                                            frame of the video to be loaded.</p></body></html>\n"
"                                                                        "))
        self.from_video_index_label.setText(_translate("ThermoGUI_main_window", "From:"))
        self.to_video_index_label.setText(_translate("ThermoGUI_main_window", "To:"))
        self.video_to_index.setToolTip(_translate("ThermoGUI_main_window", "<html><head/><body><p>Final\n"
"                                                                            frame of the video to be loaded.</p></body></html>\n"
"                                                                        "))
        self.load_video_button.setToolTip(_translate("ThermoGUI_main_window", "<html><head/><body><p>Loads\n"
"                                                                    the frames from the selected video file.</p></body></html>\n"
"                                                                "))
        self.load_video_button.setText(_translate("ThermoGUI_main_window", "Choose Video"))
        self.label_2.setText(_translate("ThermoGUI_main_window", "<html><head/><body><p\n"
"                                                                    align=\"center\"><span style=\"\n"
"                                                                    font-weight:600;\">WebCam</span></p></body></html>\n"
"                                                                "))
        self.detect_webcam_button.setToolTip(_translate("ThermoGUI_main_window", "<html><head/><body><p>Detects\n"
"                                                                    the correct port for the Webcam</p></body></html>\n"
"                                                                "))
        self.detect_webcam_button.setText(_translate("ThermoGUI_main_window", "Detect"))
        self.image_scaling_label.setText(_translate("ThermoGUI_main_window", "Input image scaling : 1.00"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.video_tab), _translate("ThermoGUI_main_window", "Video Loader"))
        self.preprocessing_label.setText(_translate("ThermoGUI_main_window", "<html><head/><body><p\n"
"                                                                    align=\"center\"><span style=\"\n"
"                                                                    font-weight:600;\">Preprocessing</span></p></body></html>\n"
"                                                                "))
        self.undistort_image_box.setText(_translate("ThermoGUI_main_window", "undistort image"))
        self.angle_label.setText(_translate("ThermoGUI_main_window", "angle:"))
        self.blur_label.setText(_translate("ThermoGUI_main_window", "blur:"))
        self.canny_parameters_label.setText(_translate("ThermoGUI_main_window", "<html><head/><body><p\n"
"                                                                    align=\"center\"><span style=\"\n"
"                                                                    font-weight:600;\">Canny</span></p></body></html>\n"
"                                                                "))
        self.histeresis_label.setText(_translate("ThermoGUI_main_window", "<html><head/><body><p>Histeresis:</p></body></html>"))
        self.label_max_histeresis.setText(_translate("ThermoGUI_main_window", "max"))
        self.label_min_histeresis.setText(_translate("ThermoGUI_main_window", "min"))
        self.dilation_label.setText(_translate("ThermoGUI_main_window", "dilation steps:"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.preprocessing_tab), _translate("ThermoGUI_main_window", "Preprocessing"))
        self.segment_label.setText(_translate("ThermoGUI_main_window", "<html><head/><body><p\n"
"                                                                    align=\"center\"><span style=\"\n"
"                                                                    font-weight:600;\">Detection</span></p></body></html>\n"
"                                                                "))
        self.max_gap_label.setText(_translate("ThermoGUI_main_window", "max gap"))
        self.delta_rho_label.setText(_translate("ThermoGUI_main_window", "delta rho"))
        self.min_votes_label.setText(_translate("ThermoGUI_main_window", "min votes"))
        self.min_length_label.setText(_translate("ThermoGUI_main_window", "min length"))
        self.delta_theta_label.setText(_translate("ThermoGUI_main_window", "delta theta"))
        self.extend_segments_label.setText(_translate("ThermoGUI_main_window", "extend segments"))
        self.clustering_label.setText(_translate("ThermoGUI_main_window", "<html><head/><body><p\n"
"                                                                    align=\"center\"><span style=\"\n"
"                                                                    font-weight:600;\">Clustering</span></p></body></html>\n"
"                                                                "))
        self.num_init_label.setText(_translate("ThermoGUI_main_window", "num init"))
        self.cluster_type_label.setText(_translate("ThermoGUI_main_window", "type"))
        self.num_clusters_label.setText(_translate("ThermoGUI_main_window", "num clusters"))
        self.gmm_value.setText(_translate("ThermoGUI_main_window", "GMM"))
        self.knn_value.setText(_translate("ThermoGUI_main_window", "KNN"))
        self.features_label.setText(_translate("ThermoGUI_main_window", "Features:"))
        self.swipe_clusters_value.setText(_translate("ThermoGUI_main_window", "swipe"))
        self.use_angle_value.setText(_translate("ThermoGUI_main_window", "angles"))
        self.use_centers_value.setText(_translate("ThermoGUI_main_window", "centers"))
        self.cleaning_label.setText(_translate("ThermoGUI_main_window", "<html><head/><body><p\n"
"                                                                    align=\"center\"><span style=\"\n"
"                                                                    font-weight:600;\">Cleaning</span></p></body></html>\n"
"                                                                "))
        self.max_merging_distance_label.setText(_translate("ThermoGUI_main_window", "max merging distance"))
        self.max_angle_variation_mean_label.setText(_translate("ThermoGUI_main_window", "max angle variation"))
        self.max_merging_angle_label.setText(_translate("ThermoGUI_main_window", "max merging angle"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.segment_tab), _translate("ThermoGUI_main_window", "Segments"))
        self.filter_label.setText(_translate("ThermoGUI_main_window", "<html><head/><body><p\n"
"                                                                    align=\"center\"><span style=\"\n"
"                                                                    font-weight:600;\">Filter</span></p></body></html>\n"
"                                                                "))
        self.ratio_max_deviation_label.setText(_translate("ThermoGUI_main_window", "ratio max deviation"))
        self.min_area_label.setText(_translate("ThermoGUI_main_window", "min area"))
        self.expected_ratio_label.setText(_translate("ThermoGUI_main_window", "expected ratio"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.module_tab), _translate("ThermoGUI_main_window", "Modules"))
        self.FileMenu.setTitle(_translate("ThermoGUI_main_window", "File"))
        self.actionLoad.setText(_translate("ThermoGUI_main_window", "Load"))
        self.file_about.setText(_translate("ThermoGUI_main_window", "About"))
        self.file_exit.setText(_translate("ThermoGUI_main_window", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ThermoGUI_main_window = QtWidgets.QMainWindow()
    ui = Ui_ThermoGUI_main_window()
    ui.setupUi(ThermoGUI_main_window)
    ThermoGUI_main_window.show()
    sys.exit(app.exec_())

