# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'thermography_gui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(755, 510)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("img/thermography.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.input_video_panel = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_video_panel.sizePolicy().hasHeightForWidth())
        self.input_video_panel.setSizePolicy(sizePolicy)
        self.input_video_panel.setFrameShape(QtGui.QFrame.NoFrame)
        self.input_video_panel.setObjectName(_fromUtf8("input_video_panel"))
        self.VideoPanel = QtGui.QVBoxLayout(self.input_video_panel)
        self.VideoPanel.setObjectName(_fromUtf8("VideoPanel"))
        self.tabWidget = QtGui.QTabWidget(self.input_video_panel)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.input_image_tab = QtGui.QWidget()
        self.input_image_tab.setObjectName(_fromUtf8("input_image_tab"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.input_image_tab)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.video_view = QtGui.QLabel(self.input_image_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.video_view.sizePolicy().hasHeightForWidth())
        self.video_view.setSizePolicy(sizePolicy)
        self.video_view.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.video_view.setFont(font)
        self.video_view.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.video_view.setMouseTracking(True)
        self.video_view.setAutoFillBackground(True)
        self.video_view.setFrameShape(QtGui.QFrame.Box)
        self.video_view.setFrameShadow(QtGui.QFrame.Plain)
        self.video_view.setTextFormat(QtCore.Qt.RichText)
        self.video_view.setScaledContents(False)
        self.video_view.setAlignment(QtCore.Qt.AlignCenter)
        self.video_view.setWordWrap(False)
        self.video_view.setObjectName(_fromUtf8("video_view"))
        self.horizontalLayout.addWidget(self.video_view)
        self.tabWidget.addTab(self.input_image_tab, _fromUtf8(""))
        self.canny_edges_tab = QtGui.QWidget()
        self.canny_edges_tab.setObjectName(_fromUtf8("canny_edges_tab"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.canny_edges_tab)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.canny_edges_view = QtGui.QLabel(self.canny_edges_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.canny_edges_view.sizePolicy().hasHeightForWidth())
        self.canny_edges_view.setSizePolicy(sizePolicy)
        self.canny_edges_view.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.canny_edges_view.setFont(font)
        self.canny_edges_view.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.canny_edges_view.setAutoFillBackground(True)
        self.canny_edges_view.setFrameShape(QtGui.QFrame.Box)
        self.canny_edges_view.setTextFormat(QtCore.Qt.RichText)
        self.canny_edges_view.setAlignment(QtCore.Qt.AlignCenter)
        self.canny_edges_view.setObjectName(_fromUtf8("canny_edges_view"))
        self.horizontalLayout_3.addWidget(self.canny_edges_view)
        self.tabWidget.addTab(self.canny_edges_tab, _fromUtf8(""))
        self.VideoPanel.addWidget(self.tabWidget)
        self.global_progress_bar = QtGui.QProgressBar(self.input_video_panel)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.global_progress_bar.sizePolicy().hasHeightForWidth())
        self.global_progress_bar.setSizePolicy(sizePolicy)
        self.global_progress_bar.setMinimumSize(QtCore.QSize(0, 10))
        self.global_progress_bar.setMaximumSize(QtCore.QSize(16777215, 10))
        self.global_progress_bar.setProperty("value", 0)
        self.global_progress_bar.setTextVisible(False)
        self.global_progress_bar.setInvertedAppearance(False)
        self.global_progress_bar.setTextDirection(QtGui.QProgressBar.TopToBottom)
        self.global_progress_bar.setObjectName(_fromUtf8("global_progress_bar"))
        self.VideoPanel.addWidget(self.global_progress_bar)
        self.horizontalLayout_2.addWidget(self.input_video_panel)
        self.control_panel = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.control_panel.sizePolicy().hasHeightForWidth())
        self.control_panel.setSizePolicy(sizePolicy)
        self.control_panel.setFrameShape(QtGui.QFrame.StyledPanel)
        self.control_panel.setFrameShadow(QtGui.QFrame.Raised)
        self.control_panel.setObjectName(_fromUtf8("control_panel"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.control_panel)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tab_widget = QtGui.QTabWidget(self.control_panel)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_widget.sizePolicy().hasHeightForWidth())
        self.tab_widget.setSizePolicy(sizePolicy)
        self.tab_widget.setTabPosition(QtGui.QTabWidget.North)
        self.tab_widget.setElideMode(QtCore.Qt.ElideNone)
        self.tab_widget.setDocumentMode(False)
        self.tab_widget.setObjectName(_fromUtf8("tab_widget"))
        self.video_tab = QtGui.QWidget()
        self.video_tab.setObjectName(_fromUtf8("video_tab"))
        self.verticalLayout = QtGui.QVBoxLayout(self.video_tab)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.video_index_panel = QtGui.QGridLayout()
        self.video_index_panel.setContentsMargins(-1, 2, -1, 2)
        self.video_index_panel.setObjectName(_fromUtf8("video_index_panel"))
        self.video_from_index = QtGui.QSpinBox(self.video_tab)
        self.video_from_index.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.video_from_index.setMaximum(100000)
        self.video_from_index.setObjectName(_fromUtf8("video_from_index"))
        self.video_index_panel.addWidget(self.video_from_index, 1, 0, 1, 1)
        self.video_to_index = QtGui.QSpinBox(self.video_tab)
        self.video_to_index.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.video_to_index.setAutoFillBackground(False)
        self.video_to_index.setMinimum(0)
        self.video_to_index.setMaximum(100000)
        self.video_to_index.setProperty("value", 500)
        self.video_to_index.setObjectName(_fromUtf8("video_to_index"))
        self.video_index_panel.addWidget(self.video_to_index, 1, 1, 1, 1)
        self.from_video_index_label = QtGui.QLabel(self.video_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.from_video_index_label.sizePolicy().hasHeightForWidth())
        self.from_video_index_label.setSizePolicy(sizePolicy)
        self.from_video_index_label.setObjectName(_fromUtf8("from_video_index_label"))
        self.video_index_panel.addWidget(self.from_video_index_label, 0, 0, 1, 1)
        self.to_video_index_label = QtGui.QLabel(self.video_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.to_video_index_label.sizePolicy().hasHeightForWidth())
        self.to_video_index_label.setSizePolicy(sizePolicy)
        self.to_video_index_label.setObjectName(_fromUtf8("to_video_index_label"))
        self.video_index_panel.addWidget(self.to_video_index_label, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.video_index_panel)
        self.load_video_button = QtGui.QPushButton(self.video_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.load_video_button.sizePolicy().hasHeightForWidth())
        self.load_video_button.setSizePolicy(sizePolicy)
        self.load_video_button.setCheckable(False)
        self.load_video_button.setDefault(True)
        self.load_video_button.setFlat(False)
        self.load_video_button.setObjectName(_fromUtf8("load_video_button"))
        self.verticalLayout.addWidget(self.load_video_button)
        self.line = QtGui.QFrame(self.video_tab)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout.addWidget(self.line)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.image_scaling_label = QtGui.QLabel(self.video_tab)
        self.image_scaling_label.setObjectName(_fromUtf8("image_scaling_label"))
        self.verticalLayout_4.addWidget(self.image_scaling_label)
        self.image_scaling_slider = QtGui.QSlider(self.video_tab)
        self.image_scaling_slider.setMinimum(1)
        self.image_scaling_slider.setMaximum(19)
        self.image_scaling_slider.setSingleStep(0)
        self.image_scaling_slider.setPageStep(1)
        self.image_scaling_slider.setProperty("value", 10)
        self.image_scaling_slider.setSliderPosition(10)
        self.image_scaling_slider.setTracking(True)
        self.image_scaling_slider.setOrientation(QtCore.Qt.Horizontal)
        self.image_scaling_slider.setTickPosition(QtGui.QSlider.TicksAbove)
        self.image_scaling_slider.setTickInterval(2)
        self.image_scaling_slider.setObjectName(_fromUtf8("image_scaling_slider"))
        self.verticalLayout_4.addWidget(self.image_scaling_slider)
        self.verticalLayout.addLayout(self.verticalLayout_4)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.tab_widget.addTab(self.video_tab, _fromUtf8(""))
        self.param_tab = QtGui.QWidget()
        self.param_tab.setObjectName(_fromUtf8("param_tab"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.param_tab)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.preprocessing_label = QtGui.QLabel(self.param_tab)
        self.preprocessing_label.setTextFormat(QtCore.Qt.RichText)
        self.preprocessing_label.setObjectName(_fromUtf8("preprocessing_label"))
        self.verticalLayout_5.addWidget(self.preprocessing_label)
        self.preprocessing_layout = QtGui.QVBoxLayout()
        self.preprocessing_layout.setContentsMargins(-1, 0, -1, -1)
        self.preprocessing_layout.setObjectName(_fromUtf8("preprocessing_layout"))
        self.undistort_image_box = QtGui.QCheckBox(self.param_tab)
        self.undistort_image_box.setChecked(True)
        self.undistort_image_box.setTristate(False)
        self.undistort_image_box.setObjectName(_fromUtf8("undistort_image_box"))
        self.preprocessing_layout.addWidget(self.undistort_image_box)
        self.preprocessing_grid_layout = QtGui.QGridLayout()
        self.preprocessing_grid_layout.setContentsMargins(-1, 10, -1, -1)
        self.preprocessing_grid_layout.setObjectName(_fromUtf8("preprocessing_grid_layout"))
        self.angle_label = QtGui.QLabel(self.param_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.angle_label.sizePolicy().hasHeightForWidth())
        self.angle_label.setSizePolicy(sizePolicy)
        self.angle_label.setObjectName(_fromUtf8("angle_label"))
        self.preprocessing_grid_layout.addWidget(self.angle_label, 0, 0, 1, 1)
        self.angle_value = QtGui.QSpinBox(self.param_tab)
        self.angle_value.setMinimum(0)
        self.angle_value.setMaximum(360)
        self.angle_value.setSingleStep(10)
        self.angle_value.setObjectName(_fromUtf8("angle_value"))
        self.preprocessing_grid_layout.addWidget(self.angle_value, 0, 1, 1, 1)
        self.blur_label = QtGui.QLabel(self.param_tab)
        self.blur_label.setObjectName(_fromUtf8("blur_label"))
        self.preprocessing_grid_layout.addWidget(self.blur_label, 1, 0, 1, 1)
        self.blur_value = QtGui.QSpinBox(self.param_tab)
        self.blur_value.setMaximum(15)
        self.blur_value.setProperty("value", 3)
        self.blur_value.setObjectName(_fromUtf8("blur_value"))
        self.preprocessing_grid_layout.addWidget(self.blur_value, 1, 1, 1, 1)
        self.preprocessing_layout.addLayout(self.preprocessing_grid_layout)
        self.verticalLayout_5.addLayout(self.preprocessing_layout)
        self.line_2 = QtGui.QFrame(self.param_tab)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout_5.addWidget(self.line_2)
        self.canny_parameters_label = QtGui.QLabel(self.param_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.canny_parameters_label.sizePolicy().hasHeightForWidth())
        self.canny_parameters_label.setSizePolicy(sizePolicy)
        self.canny_parameters_label.setTextFormat(QtCore.Qt.RichText)
        self.canny_parameters_label.setObjectName(_fromUtf8("canny_parameters_label"))
        self.verticalLayout_5.addWidget(self.canny_parameters_label)
        self.histeresis_label = QtGui.QLabel(self.param_tab)
        self.histeresis_label.setTextFormat(QtCore.Qt.RichText)
        self.histeresis_label.setObjectName(_fromUtf8("histeresis_label"))
        self.verticalLayout_5.addWidget(self.histeresis_label)
        self.histeresis_grid_layout = QtGui.QGridLayout()
        self.histeresis_grid_layout.setContentsMargins(-1, 0, -1, -1)
        self.histeresis_grid_layout.setObjectName(_fromUtf8("histeresis_grid_layout"))
        self.min_histeresis_value = QtGui.QSpinBox(self.param_tab)
        self.min_histeresis_value.setWrapping(False)
        self.min_histeresis_value.setFrame(True)
        self.min_histeresis_value.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.min_histeresis_value.setMaximum(500)
        self.min_histeresis_value.setSingleStep(10)
        self.min_histeresis_value.setProperty("value", 30)
        self.min_histeresis_value.setObjectName(_fromUtf8("min_histeresis_value"))
        self.histeresis_grid_layout.addWidget(self.min_histeresis_value, 1, 0, 1, 1)
        self.label_max_histeresis = QtGui.QLabel(self.param_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_max_histeresis.sizePolicy().hasHeightForWidth())
        self.label_max_histeresis.setSizePolicy(sizePolicy)
        self.label_max_histeresis.setMaximumSize(QtCore.QSize(16777215, 16))
        self.label_max_histeresis.setObjectName(_fromUtf8("label_max_histeresis"))
        self.histeresis_grid_layout.addWidget(self.label_max_histeresis, 0, 1, 1, 1)
        self.max_histeresis_value = QtGui.QSpinBox(self.param_tab)
        self.max_histeresis_value.setMaximum(500)
        self.max_histeresis_value.setSingleStep(10)
        self.max_histeresis_value.setProperty("value", 140)
        self.max_histeresis_value.setObjectName(_fromUtf8("max_histeresis_value"))
        self.histeresis_grid_layout.addWidget(self.max_histeresis_value, 1, 1, 1, 1)
        self.label_min_histeresis = QtGui.QLabel(self.param_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_min_histeresis.sizePolicy().hasHeightForWidth())
        self.label_min_histeresis.setSizePolicy(sizePolicy)
        self.label_min_histeresis.setMaximumSize(QtCore.QSize(16777215, 16))
        self.label_min_histeresis.setObjectName(_fromUtf8("label_min_histeresis"))
        self.histeresis_grid_layout.addWidget(self.label_min_histeresis, 0, 0, 1, 1)
        self.verticalLayout_5.addLayout(self.histeresis_grid_layout)
        self.dilation_layout = QtGui.QHBoxLayout()
        self.dilation_layout.setContentsMargins(-1, 0, -1, -1)
        self.dilation_layout.setObjectName(_fromUtf8("dilation_layout"))
        self.dilation_label = QtGui.QLabel(self.param_tab)
        self.dilation_label.setObjectName(_fromUtf8("dilation_label"))
        self.dilation_layout.addWidget(self.dilation_label)
        self.dilation_value = QtGui.QSpinBox(self.param_tab)
        self.dilation_value.setMaximum(10)
        self.dilation_value.setObjectName(_fromUtf8("dilation_value"))
        self.dilation_layout.addWidget(self.dilation_value)
        self.verticalLayout_5.addLayout(self.dilation_layout)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.tab_widget.addTab(self.param_tab, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.tab_widget)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.play_stop_panel = QtGui.QVBoxLayout()
        self.play_stop_panel.setContentsMargins(-1, 0, -1, 0)
        self.play_stop_panel.setObjectName(_fromUtf8("play_stop_panel"))
        self.play_stop_buttons_panel = QtGui.QHBoxLayout()
        self.play_stop_buttons_panel.setContentsMargins(-1, 0, -1, 0)
        self.play_stop_buttons_panel.setObjectName(_fromUtf8("play_stop_buttons_panel"))
        self.play_video_button = QtGui.QPushButton(self.control_panel)
        self.play_video_button.setCheckable(False)
        self.play_video_button.setObjectName(_fromUtf8("play_video_button"))
        self.play_stop_buttons_panel.addWidget(self.play_video_button)
        self.stop_video_button = QtGui.QPushButton(self.control_panel)
        self.stop_video_button.setEnabled(False)
        self.stop_video_button.setCheckable(False)
        self.stop_video_button.setChecked(False)
        self.stop_video_button.setObjectName(_fromUtf8("stop_video_button"))
        self.play_stop_buttons_panel.addWidget(self.stop_video_button)
        self.play_stop_panel.addLayout(self.play_stop_buttons_panel)
        self.reset_button = QtGui.QPushButton(self.control_panel)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.reset_button.setFont(font)
        self.reset_button.setAutoFillBackground(False)
        self.reset_button.setAutoDefault(False)
        self.reset_button.setDefault(False)
        self.reset_button.setFlat(False)
        self.reset_button.setObjectName(_fromUtf8("reset_button"))
        self.play_stop_panel.addWidget(self.reset_button)
        self.verticalLayout_2.addLayout(self.play_stop_panel)
        self.horizontalLayout_2.addWidget(self.control_panel, QtCore.Qt.AlignTop)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.tab_widget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Thermography", None))
        self.video_view.setText(_translate("MainWindow", "Video", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.input_image_tab), _translate("MainWindow", "Input image", None))
        self.canny_edges_view.setText(_translate("MainWindow", "Processed Image", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.canny_edges_tab), _translate("MainWindow", "Processed image", None))
        self.global_progress_bar.setFormat(_translate("MainWindow", "%p%", None))
        self.from_video_index_label.setText(_translate("MainWindow", "From:", None))
        self.to_video_index_label.setText(_translate("MainWindow", "To:", None))
        self.load_video_button.setText(_translate("MainWindow", "Choose Video", None))
        self.image_scaling_label.setText(_translate("MainWindow", "Input image scaling : 1.00", None))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.video_tab), _translate("MainWindow", "Video Loader", None))
        self.preprocessing_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Preprocessing</span></p></body></html>", None))
        self.undistort_image_box.setText(_translate("MainWindow", "undistort image", None))
        self.angle_label.setText(_translate("MainWindow", "angle:", None))
        self.blur_label.setText(_translate("MainWindow", "blur:", None))
        self.canny_parameters_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Canny</span></p></body></html>", None))
        self.histeresis_label.setText(_translate("MainWindow", "<html><head/><body><p>Histeresis:</p></body></html>", None))
        self.label_max_histeresis.setText(_translate("MainWindow", "max", None))
        self.label_min_histeresis.setText(_translate("MainWindow", "min", None))
        self.dilation_label.setText(_translate("MainWindow", "dilation steps: ", None))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.param_tab), _translate("MainWindow", "Parameters", None))
        self.play_video_button.setText(_translate("MainWindow", "Play", None))
        self.stop_video_button.setText(_translate("MainWindow", "Stop", None))
        self.reset_button.setText(_translate("MainWindow", "Reset", None))

