# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'thermography_gui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(844, 540)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("git/thermography/gui/img/thermography.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.input_video_panel = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_video_panel.sizePolicy().hasHeightForWidth())
        self.input_video_panel.setSizePolicy(sizePolicy)
        self.input_video_panel.setFrameShape(QtGui.QFrame.NoFrame)
        self.input_video_panel.setObjectName(_fromUtf8("input_video_panel"))
        self.VideoPanel = QtGui.QVBoxLayout(self.input_video_panel)
        self.VideoPanel.setObjectName(_fromUtf8("VideoPanel"))
        self.video_view = QtGui.QLabel(self.input_video_panel)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.video_view.sizePolicy().hasHeightForWidth())
        self.video_view.setSizePolicy(sizePolicy)
        self.video_view.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.video_view.setFont(font)
        self.video_view.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.video_view.setMouseTracking(False)
        self.video_view.setAutoFillBackground(True)
        self.video_view.setFrameShape(QtGui.QFrame.Box)
        self.video_view.setFrameShadow(QtGui.QFrame.Plain)
        self.video_view.setTextFormat(QtCore.Qt.RichText)
        self.video_view.setScaledContents(False)
        self.video_view.setAlignment(QtCore.Qt.AlignCenter)
        self.video_view.setWordWrap(False)
        self.video_view.setObjectName(_fromUtf8("video_view"))
        self.VideoPanel.addWidget(self.video_view)
        self.global_progress_bar = QtGui.QProgressBar(self.input_video_panel)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.global_progress_bar.sizePolicy().hasHeightForWidth())
        self.global_progress_bar.setSizePolicy(sizePolicy)
        self.global_progress_bar.setMinimumSize(QtCore.QSize(0, 10))
        self.global_progress_bar.setMaximumSize(QtCore.QSize(16777215, 10))
        self.global_progress_bar.setProperty("value", 0)
        self.global_progress_bar.setTextVisible(False)
        self.global_progress_bar.setInvertedAppearance(False)
        self.global_progress_bar.setTextDirection(QtGui.QProgressBar.TopToBottom)
        self.global_progress_bar.setObjectName(_fromUtf8("global_progress_bar"))
        self.VideoPanel.addWidget(self.global_progress_bar)
        self.horizontalLayout_2.addWidget(self.input_video_panel)
        self.processed_video_panel = QtGui.QFrame(self.centralwidget)
        self.processed_video_panel.setFrameShape(QtGui.QFrame.StyledPanel)
        self.processed_video_panel.setFrameShadow(QtGui.QFrame.Raised)
        self.processed_video_panel.setObjectName(_fromUtf8("processed_video_panel"))
        self.verticalLayout = QtGui.QVBoxLayout(self.processed_video_panel)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.canny_edges_video = QtGui.QLabel(self.processed_video_panel)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.canny_edges_video.sizePolicy().hasHeightForWidth())
        self.canny_edges_video.setSizePolicy(sizePolicy)
        self.canny_edges_video.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.canny_edges_video.setAutoFillBackground(True)
        self.canny_edges_video.setFrameShape(QtGui.QFrame.Box)
        self.canny_edges_video.setMidLineWidth(0)
        self.canny_edges_video.setTextFormat(QtCore.Qt.RichText)
        self.canny_edges_video.setAlignment(QtCore.Qt.AlignCenter)
        self.canny_edges_video.setWordWrap(False)
        self.canny_edges_video.setObjectName(_fromUtf8("canny_edges_video"))
        self.verticalLayout.addWidget(self.canny_edges_video)
        self.horizontalLayout_2.addWidget(self.processed_video_panel)
        self.tools_panel = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tools_panel.sizePolicy().hasHeightForWidth())
        self.tools_panel.setSizePolicy(sizePolicy)
        self.tools_panel.setMinimumSize(QtCore.QSize(0, 0))
        self.tools_panel.setFrameShape(QtGui.QFrame.StyledPanel)
        self.tools_panel.setFrameShadow(QtGui.QFrame.Raised)
        self.tools_panel.setObjectName(_fromUtf8("tools_panel"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tools_panel)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.video_index_panel = QtGui.QGridLayout()
        self.video_index_panel.setContentsMargins(-1, 2, -1, 2)
        self.video_index_panel.setObjectName(_fromUtf8("video_index_panel"))
        self.video_from_index = QtGui.QSpinBox(self.tools_panel)
        self.video_from_index.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.video_from_index.setMaximum(100000)
        self.video_from_index.setObjectName(_fromUtf8("video_from_index"))
        self.video_index_panel.addWidget(self.video_from_index, 1, 0, 1, 1)
        self.video_to_index = QtGui.QSpinBox(self.tools_panel)
        self.video_to_index.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.video_to_index.setAutoFillBackground(False)
        self.video_to_index.setMinimum(0)
        self.video_to_index.setMaximum(100000)
        self.video_to_index.setProperty("value", 500)
        self.video_to_index.setObjectName(_fromUtf8("video_to_index"))
        self.video_index_panel.addWidget(self.video_to_index, 1, 1, 1, 1)
        self.from_video_index_label = QtGui.QLabel(self.tools_panel)
        self.from_video_index_label.setObjectName(_fromUtf8("from_video_index_label"))
        self.video_index_panel.addWidget(self.from_video_index_label, 0, 0, 1, 1)
        self.to_video_index_label = QtGui.QLabel(self.tools_panel)
        self.to_video_index_label.setObjectName(_fromUtf8("to_video_index_label"))
        self.video_index_panel.addWidget(self.to_video_index_label, 0, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.video_index_panel)
        self.load_video_button = QtGui.QPushButton(self.tools_panel)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.load_video_button.sizePolicy().hasHeightForWidth())
        self.load_video_button.setSizePolicy(sizePolicy)
        self.load_video_button.setCheckable(False)
        self.load_video_button.setFlat(False)
        self.load_video_button.setObjectName(_fromUtf8("load_video_button"))
        self.verticalLayout_2.addWidget(self.load_video_button)
        self.play_stop_buttons_panel = QtGui.QHBoxLayout()
        self.play_stop_buttons_panel.setContentsMargins(-1, 0, -1, 0)
        self.play_stop_buttons_panel.setObjectName(_fromUtf8("play_stop_buttons_panel"))
        self.play_video_button = QtGui.QPushButton(self.tools_panel)
        self.play_video_button.setCheckable(False)
        self.play_video_button.setObjectName(_fromUtf8("play_video_button"))
        self.play_stop_buttons_panel.addWidget(self.play_video_button)
        self.stop_video_button = QtGui.QPushButton(self.tools_panel)
        self.stop_video_button.setEnabled(False)
        self.stop_video_button.setCheckable(False)
        self.stop_video_button.setChecked(False)
        self.stop_video_button.setObjectName(_fromUtf8("stop_video_button"))
        self.play_stop_buttons_panel.addWidget(self.stop_video_button)
        self.verticalLayout_2.addLayout(self.play_stop_buttons_panel)
        self.horizontalLayout_2.addWidget(self.tools_panel, QtCore.Qt.AlignTop)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Thermography", None))
        self.video_view.setText(_translate("MainWindow", "Video", None))
        self.global_progress_bar.setFormat(_translate("MainWindow", "%p%", None))
        self.canny_edges_video.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Canny Edges</span></p></body></html>", None))
        self.from_video_index_label.setText(_translate("MainWindow", "From:", None))
        self.to_video_index_label.setText(_translate("MainWindow", "To:", None))
        self.load_video_button.setText(_translate("MainWindow", "Choose Video", None))
        self.play_video_button.setText(_translate("MainWindow", "Play", None))
        self.stop_video_button.setText(_translate("MainWindow", "Stop", None))

