# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'thermography_gui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(793, 670)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("img/thermography.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.input_video_panel = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_video_panel.sizePolicy().hasHeightForWidth())
        self.input_video_panel.setSizePolicy(sizePolicy)
        self.input_video_panel.setFrameShape(QtGui.QFrame.NoFrame)
        self.input_video_panel.setObjectName(_fromUtf8("input_video_panel"))
        self.VideoPanel = QtGui.QVBoxLayout(self.input_video_panel)
        self.VideoPanel.setObjectName(_fromUtf8("VideoPanel"))
        self.tabWidget = QtGui.QTabWidget(self.input_video_panel)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.input_image_tab = QtGui.QWidget()
        self.input_image_tab.setObjectName(_fromUtf8("input_image_tab"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.input_image_tab)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.video_view = QtGui.QLabel(self.input_image_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.video_view.sizePolicy().hasHeightForWidth())
        self.video_view.setSizePolicy(sizePolicy)
        self.video_view.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.video_view.setFont(font)
        self.video_view.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.video_view.setMouseTracking(True)
        self.video_view.setAutoFillBackground(True)
        self.video_view.setFrameShape(QtGui.QFrame.Box)
        self.video_view.setFrameShadow(QtGui.QFrame.Plain)
        self.video_view.setTextFormat(QtCore.Qt.RichText)
        self.video_view.setScaledContents(False)
        self.video_view.setAlignment(QtCore.Qt.AlignCenter)
        self.video_view.setWordWrap(False)
        self.video_view.setObjectName(_fromUtf8("video_view"))
        self.horizontalLayout.addWidget(self.video_view)
        self.tabWidget.addTab(self.input_image_tab, _fromUtf8(""))
        self.canny_edges_tab = QtGui.QWidget()
        self.canny_edges_tab.setObjectName(_fromUtf8("canny_edges_tab"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.canny_edges_tab)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.canny_edges_view = QtGui.QLabel(self.canny_edges_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.canny_edges_view.sizePolicy().hasHeightForWidth())
        self.canny_edges_view.setSizePolicy(sizePolicy)
        self.canny_edges_view.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.canny_edges_view.setFont(font)
        self.canny_edges_view.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.canny_edges_view.setAutoFillBackground(True)
        self.canny_edges_view.setFrameShape(QtGui.QFrame.Box)
        self.canny_edges_view.setTextFormat(QtCore.Qt.RichText)
        self.canny_edges_view.setAlignment(QtCore.Qt.AlignCenter)
        self.canny_edges_view.setObjectName(_fromUtf8("canny_edges_view"))
        self.horizontalLayout_3.addWidget(self.canny_edges_view)
        self.tabWidget.addTab(self.canny_edges_tab, _fromUtf8(""))
        self.segment_image_tab = QtGui.QWidget()
        self.segment_image_tab.setObjectName(_fromUtf8("segment_image_tab"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.segment_image_tab)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.segment_image_view = QtGui.QLabel(self.segment_image_tab)
        font = QtGui.QFont()
        font.setPointSize(26)
        self.segment_image_view.setFont(font)
        self.segment_image_view.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.segment_image_view.setAutoFillBackground(True)
        self.segment_image_view.setFrameShape(QtGui.QFrame.Box)
        self.segment_image_view.setTextFormat(QtCore.Qt.RichText)
        self.segment_image_view.setObjectName(_fromUtf8("segment_image_view"))
        self.horizontalLayout_5.addWidget(self.segment_image_view)
        self.tabWidget.addTab(self.segment_image_tab, _fromUtf8(""))
        self.module_image_tab = QtGui.QWidget()
        self.module_image_tab.setObjectName(_fromUtf8("module_image_tab"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.module_image_tab)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.module_image_view = QtGui.QLabel(self.module_image_tab)
        font = QtGui.QFont()
        font.setPointSize(26)
        self.module_image_view.setFont(font)
        self.module_image_view.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.module_image_view.setMouseTracking(True)
        self.module_image_view.setAutoFillBackground(True)
        self.module_image_view.setFrameShape(QtGui.QFrame.Box)
        self.module_image_view.setTextFormat(QtCore.Qt.RichText)
        self.module_image_view.setScaledContents(False)
        self.module_image_view.setObjectName(_fromUtf8("module_image_view"))
        self.horizontalLayout_4.addWidget(self.module_image_view)
        self.tabWidget.addTab(self.module_image_tab, _fromUtf8(""))
        self.VideoPanel.addWidget(self.tabWidget)
        self.global_progress_bar = QtGui.QProgressBar(self.input_video_panel)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.global_progress_bar.sizePolicy().hasHeightForWidth())
        self.global_progress_bar.setSizePolicy(sizePolicy)
        self.global_progress_bar.setMinimumSize(QtCore.QSize(0, 10))
        self.global_progress_bar.setMaximumSize(QtCore.QSize(16777215, 10))
        self.global_progress_bar.setProperty("value", 0)
        self.global_progress_bar.setTextVisible(False)
        self.global_progress_bar.setInvertedAppearance(False)
        self.global_progress_bar.setTextDirection(QtGui.QProgressBar.TopToBottom)
        self.global_progress_bar.setObjectName(_fromUtf8("global_progress_bar"))
        self.VideoPanel.addWidget(self.global_progress_bar)
        self.horizontalLayout_2.addWidget(self.input_video_panel)
        self.control_panel = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.control_panel.sizePolicy().hasHeightForWidth())
        self.control_panel.setSizePolicy(sizePolicy)
        self.control_panel.setFrameShape(QtGui.QFrame.StyledPanel)
        self.control_panel.setFrameShadow(QtGui.QFrame.Raised)
        self.control_panel.setObjectName(_fromUtf8("control_panel"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.control_panel)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tab_widget = QtGui.QTabWidget(self.control_panel)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_widget.sizePolicy().hasHeightForWidth())
        self.tab_widget.setSizePolicy(sizePolicy)
        self.tab_widget.setTabPosition(QtGui.QTabWidget.North)
        self.tab_widget.setElideMode(QtCore.Qt.ElideNone)
        self.tab_widget.setDocumentMode(False)
        self.tab_widget.setObjectName(_fromUtf8("tab_widget"))
        self.video_tab = QtGui.QWidget()
        self.video_tab.setObjectName(_fromUtf8("video_tab"))
        self.verticalLayout = QtGui.QVBoxLayout(self.video_tab)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.video_index_panel = QtGui.QGridLayout()
        self.video_index_panel.setContentsMargins(-1, 2, -1, 2)
        self.video_index_panel.setObjectName(_fromUtf8("video_index_panel"))
        self.video_from_index = QtGui.QSpinBox(self.video_tab)
        self.video_from_index.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.video_from_index.setMaximum(100000)
        self.video_from_index.setObjectName(_fromUtf8("video_from_index"))
        self.video_index_panel.addWidget(self.video_from_index, 1, 0, 1, 1)
        self.video_to_index = QtGui.QSpinBox(self.video_tab)
        self.video_to_index.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.video_to_index.setAutoFillBackground(False)
        self.video_to_index.setMinimum(0)
        self.video_to_index.setMaximum(100000)
        self.video_to_index.setProperty("value", 500)
        self.video_to_index.setObjectName(_fromUtf8("video_to_index"))
        self.video_index_panel.addWidget(self.video_to_index, 1, 1, 1, 1)
        self.from_video_index_label = QtGui.QLabel(self.video_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.from_video_index_label.sizePolicy().hasHeightForWidth())
        self.from_video_index_label.setSizePolicy(sizePolicy)
        self.from_video_index_label.setObjectName(_fromUtf8("from_video_index_label"))
        self.video_index_panel.addWidget(self.from_video_index_label, 0, 0, 1, 1)
        self.to_video_index_label = QtGui.QLabel(self.video_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.to_video_index_label.sizePolicy().hasHeightForWidth())
        self.to_video_index_label.setSizePolicy(sizePolicy)
        self.to_video_index_label.setObjectName(_fromUtf8("to_video_index_label"))
        self.video_index_panel.addWidget(self.to_video_index_label, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.video_index_panel)
        self.load_video_button = QtGui.QPushButton(self.video_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.load_video_button.sizePolicy().hasHeightForWidth())
        self.load_video_button.setSizePolicy(sizePolicy)
        self.load_video_button.setCheckable(False)
        self.load_video_button.setDefault(True)
        self.load_video_button.setFlat(False)
        self.load_video_button.setObjectName(_fromUtf8("load_video_button"))
        self.verticalLayout.addWidget(self.load_video_button)
        self.line = QtGui.QFrame(self.video_tab)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout.addWidget(self.line)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.image_scaling_label = QtGui.QLabel(self.video_tab)
        self.image_scaling_label.setObjectName(_fromUtf8("image_scaling_label"))
        self.verticalLayout_4.addWidget(self.image_scaling_label)
        self.image_scaling_slider = QtGui.QSlider(self.video_tab)
        self.image_scaling_slider.setMinimum(1)
        self.image_scaling_slider.setMaximum(19)
        self.image_scaling_slider.setSingleStep(0)
        self.image_scaling_slider.setPageStep(1)
        self.image_scaling_slider.setProperty("value", 10)
        self.image_scaling_slider.setSliderPosition(10)
        self.image_scaling_slider.setTracking(True)
        self.image_scaling_slider.setOrientation(QtCore.Qt.Horizontal)
        self.image_scaling_slider.setTickPosition(QtGui.QSlider.TicksAbove)
        self.image_scaling_slider.setTickInterval(2)
        self.image_scaling_slider.setObjectName(_fromUtf8("image_scaling_slider"))
        self.verticalLayout_4.addWidget(self.image_scaling_slider)
        self.verticalLayout.addLayout(self.verticalLayout_4)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.tab_widget.addTab(self.video_tab, _fromUtf8(""))
        self.preprocessing_tab = QtGui.QWidget()
        self.preprocessing_tab.setObjectName(_fromUtf8("preprocessing_tab"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.preprocessing_tab)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.preprocessing_label = QtGui.QLabel(self.preprocessing_tab)
        self.preprocessing_label.setTextFormat(QtCore.Qt.RichText)
        self.preprocessing_label.setObjectName(_fromUtf8("preprocessing_label"))
        self.verticalLayout_5.addWidget(self.preprocessing_label)
        self.preprocessing_layout = QtGui.QVBoxLayout()
        self.preprocessing_layout.setContentsMargins(-1, 0, -1, -1)
        self.preprocessing_layout.setObjectName(_fromUtf8("preprocessing_layout"))
        self.undistort_image_box = QtGui.QCheckBox(self.preprocessing_tab)
        self.undistort_image_box.setChecked(True)
        self.undistort_image_box.setTristate(False)
        self.undistort_image_box.setObjectName(_fromUtf8("undistort_image_box"))
        self.preprocessing_layout.addWidget(self.undistort_image_box)
        self.preprocessing_grid_layout = QtGui.QGridLayout()
        self.preprocessing_grid_layout.setContentsMargins(-1, 10, -1, -1)
        self.preprocessing_grid_layout.setObjectName(_fromUtf8("preprocessing_grid_layout"))
        self.angle_label = QtGui.QLabel(self.preprocessing_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.angle_label.sizePolicy().hasHeightForWidth())
        self.angle_label.setSizePolicy(sizePolicy)
        self.angle_label.setObjectName(_fromUtf8("angle_label"))
        self.preprocessing_grid_layout.addWidget(self.angle_label, 0, 0, 1, 1)
        self.angle_value = QtGui.QSpinBox(self.preprocessing_tab)
        self.angle_value.setMinimum(0)
        self.angle_value.setMaximum(360)
        self.angle_value.setSingleStep(10)
        self.angle_value.setObjectName(_fromUtf8("angle_value"))
        self.preprocessing_grid_layout.addWidget(self.angle_value, 0, 1, 1, 1)
        self.blur_label = QtGui.QLabel(self.preprocessing_tab)
        self.blur_label.setObjectName(_fromUtf8("blur_label"))
        self.preprocessing_grid_layout.addWidget(self.blur_label, 1, 0, 1, 1)
        self.blur_value = QtGui.QSpinBox(self.preprocessing_tab)
        self.blur_value.setMaximum(15)
        self.blur_value.setProperty("value", 3)
        self.blur_value.setObjectName(_fromUtf8("blur_value"))
        self.preprocessing_grid_layout.addWidget(self.blur_value, 1, 1, 1, 1)
        self.preprocessing_layout.addLayout(self.preprocessing_grid_layout)
        self.verticalLayout_5.addLayout(self.preprocessing_layout)
        self.line_2 = QtGui.QFrame(self.preprocessing_tab)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout_5.addWidget(self.line_2)
        self.canny_parameters_label = QtGui.QLabel(self.preprocessing_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.canny_parameters_label.sizePolicy().hasHeightForWidth())
        self.canny_parameters_label.setSizePolicy(sizePolicy)
        self.canny_parameters_label.setTextFormat(QtCore.Qt.RichText)
        self.canny_parameters_label.setObjectName(_fromUtf8("canny_parameters_label"))
        self.verticalLayout_5.addWidget(self.canny_parameters_label)
        self.histeresis_label = QtGui.QLabel(self.preprocessing_tab)
        self.histeresis_label.setTextFormat(QtCore.Qt.RichText)
        self.histeresis_label.setObjectName(_fromUtf8("histeresis_label"))
        self.verticalLayout_5.addWidget(self.histeresis_label)
        self.histeresis_grid_layout = QtGui.QGridLayout()
        self.histeresis_grid_layout.setContentsMargins(-1, 0, -1, -1)
        self.histeresis_grid_layout.setObjectName(_fromUtf8("histeresis_grid_layout"))
        self.min_histeresis_value = QtGui.QSpinBox(self.preprocessing_tab)
        self.min_histeresis_value.setWrapping(False)
        self.min_histeresis_value.setFrame(True)
        self.min_histeresis_value.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.min_histeresis_value.setMaximum(500)
        self.min_histeresis_value.setSingleStep(10)
        self.min_histeresis_value.setProperty("value", 30)
        self.min_histeresis_value.setObjectName(_fromUtf8("min_histeresis_value"))
        self.histeresis_grid_layout.addWidget(self.min_histeresis_value, 1, 0, 1, 1)
        self.label_max_histeresis = QtGui.QLabel(self.preprocessing_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_max_histeresis.sizePolicy().hasHeightForWidth())
        self.label_max_histeresis.setSizePolicy(sizePolicy)
        self.label_max_histeresis.setMaximumSize(QtCore.QSize(16777215, 16))
        self.label_max_histeresis.setObjectName(_fromUtf8("label_max_histeresis"))
        self.histeresis_grid_layout.addWidget(self.label_max_histeresis, 0, 1, 1, 1)
        self.max_histeresis_value = QtGui.QSpinBox(self.preprocessing_tab)
        self.max_histeresis_value.setMaximum(500)
        self.max_histeresis_value.setSingleStep(10)
        self.max_histeresis_value.setProperty("value", 140)
        self.max_histeresis_value.setObjectName(_fromUtf8("max_histeresis_value"))
        self.histeresis_grid_layout.addWidget(self.max_histeresis_value, 1, 1, 1, 1)
        self.label_min_histeresis = QtGui.QLabel(self.preprocessing_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_min_histeresis.sizePolicy().hasHeightForWidth())
        self.label_min_histeresis.setSizePolicy(sizePolicy)
        self.label_min_histeresis.setMaximumSize(QtCore.QSize(16777215, 16))
        self.label_min_histeresis.setObjectName(_fromUtf8("label_min_histeresis"))
        self.histeresis_grid_layout.addWidget(self.label_min_histeresis, 0, 0, 1, 1)
        self.verticalLayout_5.addLayout(self.histeresis_grid_layout)
        self.dilation_layout = QtGui.QHBoxLayout()
        self.dilation_layout.setContentsMargins(-1, 0, -1, -1)
        self.dilation_layout.setObjectName(_fromUtf8("dilation_layout"))
        self.dilation_label = QtGui.QLabel(self.preprocessing_tab)
        self.dilation_label.setObjectName(_fromUtf8("dilation_label"))
        self.dilation_layout.addWidget(self.dilation_label)
        self.dilation_value = QtGui.QSpinBox(self.preprocessing_tab)
        self.dilation_value.setMaximum(10)
        self.dilation_value.setProperty("value", 3)
        self.dilation_value.setObjectName(_fromUtf8("dilation_value"))
        self.dilation_layout.addWidget(self.dilation_value)
        self.verticalLayout_5.addLayout(self.dilation_layout)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.tab_widget.addTab(self.preprocessing_tab, _fromUtf8(""))
        self.segment_tab = QtGui.QWidget()
        self.segment_tab.setObjectName(_fromUtf8("segment_tab"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.segment_tab)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.segment_label = QtGui.QLabel(self.segment_tab)
        self.segment_label.setTextFormat(QtCore.Qt.RichText)
        self.segment_label.setObjectName(_fromUtf8("segment_label"))
        self.verticalLayout_7.addWidget(self.segment_label)
        self.detection_layout = QtGui.QGridLayout()
        self.detection_layout.setContentsMargins(-1, 0, -1, -1)
        self.detection_layout.setObjectName(_fromUtf8("detection_layout"))
        self.max_gap_value = QtGui.QSpinBox(self.segment_tab)
        self.max_gap_value.setMaximum(500)
        self.max_gap_value.setSingleStep(10)
        self.max_gap_value.setProperty("value", 150)
        self.max_gap_value.setObjectName(_fromUtf8("max_gap_value"))
        self.detection_layout.addWidget(self.max_gap_value, 4, 1, 1, 1)
        self.max_gap_label = QtGui.QLabel(self.segment_tab)
        self.max_gap_label.setObjectName(_fromUtf8("max_gap_label"))
        self.detection_layout.addWidget(self.max_gap_label, 4, 0, 1, 1)
        self.min_length_value = QtGui.QSpinBox(self.segment_tab)
        self.min_length_value.setMinimum(0)
        self.min_length_value.setMaximum(500)
        self.min_length_value.setSingleStep(10)
        self.min_length_value.setProperty("value", 50)
        self.min_length_value.setObjectName(_fromUtf8("min_length_value"))
        self.detection_layout.addWidget(self.min_length_value, 3, 1, 1, 1)
        self.delta_rho_label = QtGui.QLabel(self.segment_tab)
        self.delta_rho_label.setObjectName(_fromUtf8("delta_rho_label"))
        self.detection_layout.addWidget(self.delta_rho_label, 0, 0, 1, 1)
        self.min_votes_value = QtGui.QSpinBox(self.segment_tab)
        self.min_votes_value.setMinimum(0)
        self.min_votes_value.setMaximum(500)
        self.min_votes_value.setSingleStep(10)
        self.min_votes_value.setProperty("value", 60)
        self.min_votes_value.setObjectName(_fromUtf8("min_votes_value"))
        self.detection_layout.addWidget(self.min_votes_value, 2, 1, 1, 1)
        self.delta_theta_value = QtGui.QSpinBox(self.segment_tab)
        self.delta_theta_value.setMinimum(1)
        self.delta_theta_value.setMaximum(180)
        self.delta_theta_value.setProperty("value", 1)
        self.delta_theta_value.setObjectName(_fromUtf8("delta_theta_value"))
        self.detection_layout.addWidget(self.delta_theta_value, 1, 1, 1, 1)
        self.min_votes_label = QtGui.QLabel(self.segment_tab)
        self.min_votes_label.setObjectName(_fromUtf8("min_votes_label"))
        self.detection_layout.addWidget(self.min_votes_label, 2, 0, 1, 1)
        self.delta_rho_value = QtGui.QSpinBox(self.segment_tab)
        self.delta_rho_value.setMinimum(1)
        self.delta_rho_value.setMaximum(100)
        self.delta_rho_value.setProperty("value", 1)
        self.delta_rho_value.setObjectName(_fromUtf8("delta_rho_value"))
        self.detection_layout.addWidget(self.delta_rho_value, 0, 1, 1, 1)
        self.min_length_label = QtGui.QLabel(self.segment_tab)
        self.min_length_label.setObjectName(_fromUtf8("min_length_label"))
        self.detection_layout.addWidget(self.min_length_label, 3, 0, 1, 1)
        self.delta_theta_label = QtGui.QLabel(self.segment_tab)
        self.delta_theta_label.setObjectName(_fromUtf8("delta_theta_label"))
        self.detection_layout.addWidget(self.delta_theta_label, 1, 0, 1, 1)
        self.extend_segments_label = QtGui.QLabel(self.segment_tab)
        self.extend_segments_label.setObjectName(_fromUtf8("extend_segments_label"))
        self.detection_layout.addWidget(self.extend_segments_label, 5, 0, 1, 1)
        self.extend_segments_value = QtGui.QSpinBox(self.segment_tab)
        self.extend_segments_value.setMaximum(500)
        self.extend_segments_value.setProperty("value", 10)
        self.extend_segments_value.setObjectName(_fromUtf8("extend_segments_value"))
        self.detection_layout.addWidget(self.extend_segments_value, 5, 1, 1, 1)
        self.verticalLayout_7.addLayout(self.detection_layout)
        self.line_3 = QtGui.QFrame(self.segment_tab)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout_7.addWidget(self.line_3)
        self.clustering_label = QtGui.QLabel(self.segment_tab)
        self.clustering_label.setTextFormat(QtCore.Qt.RichText)
        self.clustering_label.setObjectName(_fromUtf8("clustering_label"))
        self.verticalLayout_7.addWidget(self.clustering_label)
        self.clustering_layout = QtGui.QGridLayout()
        self.clustering_layout.setContentsMargins(-1, 0, -1, -1)
        self.clustering_layout.setObjectName(_fromUtf8("clustering_layout"))
        self.num_init_label = QtGui.QLabel(self.segment_tab)
        self.num_init_label.setObjectName(_fromUtf8("num_init_label"))
        self.clustering_layout.addWidget(self.num_init_label, 2, 0, 1, 1)
        self.cluster_type_label = QtGui.QLabel(self.segment_tab)
        self.cluster_type_label.setObjectName(_fromUtf8("cluster_type_label"))
        self.clustering_layout.addWidget(self.cluster_type_label, 0, 0, 1, 1)
        self.num_clusters_value = QtGui.QSpinBox(self.segment_tab)
        self.num_clusters_value.setMinimum(2)
        self.num_clusters_value.setObjectName(_fromUtf8("num_clusters_value"))
        self.clustering_layout.addWidget(self.num_clusters_value, 1, 1, 1, 1)
        self.num_init_value = QtGui.QSpinBox(self.segment_tab)
        self.num_init_value.setEnabled(False)
        self.num_init_value.setMinimum(1)
        self.num_init_value.setProperty("value", 5)
        self.num_init_value.setObjectName(_fromUtf8("num_init_value"))
        self.clustering_layout.addWidget(self.num_init_value, 2, 1, 1, 1)
        self.num_clusters_label = QtGui.QLabel(self.segment_tab)
        self.num_clusters_label.setObjectName(_fromUtf8("num_clusters_label"))
        self.clustering_layout.addWidget(self.num_clusters_label, 1, 0, 1, 1)
        self.cluster_type_layout = QtGui.QHBoxLayout()
        self.cluster_type_layout.setObjectName(_fromUtf8("cluster_type_layout"))
        self.gmm_value = QtGui.QRadioButton(self.segment_tab)
        self.gmm_value.setChecked(True)
        self.gmm_value.setObjectName(_fromUtf8("gmm_value"))
        self.cluster_type_layout.addWidget(self.gmm_value)
        self.knn_value = QtGui.QRadioButton(self.segment_tab)
        self.knn_value.setObjectName(_fromUtf8("knn_value"))
        self.cluster_type_layout.addWidget(self.knn_value)
        self.clustering_layout.addLayout(self.cluster_type_layout, 0, 1, 1, 1)
        self.verticalLayout_7.addLayout(self.clustering_layout)
        self.features_label = QtGui.QLabel(self.segment_tab)
        self.features_label.setObjectName(_fromUtf8("features_label"))
        self.verticalLayout_7.addWidget(self.features_label)
        self.features_layout = QtGui.QHBoxLayout()
        self.features_layout.setContentsMargins(-1, 0, -1, -1)
        self.features_layout.setObjectName(_fromUtf8("features_layout"))
        self.swipe_clusters_value = QtGui.QCheckBox(self.segment_tab)
        self.swipe_clusters_value.setObjectName(_fromUtf8("swipe_clusters_value"))
        self.features_layout.addWidget(self.swipe_clusters_value)
        self.use_angle_value = QtGui.QCheckBox(self.segment_tab)
        self.use_angle_value.setChecked(True)
        self.use_angle_value.setObjectName(_fromUtf8("use_angle_value"))
        self.features_layout.addWidget(self.use_angle_value)
        self.use_centers_value = QtGui.QCheckBox(self.segment_tab)
        self.use_centers_value.setObjectName(_fromUtf8("use_centers_value"))
        self.features_layout.addWidget(self.use_centers_value)
        self.verticalLayout_7.addLayout(self.features_layout)
        self.line_4 = QtGui.QFrame(self.segment_tab)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.verticalLayout_7.addWidget(self.line_4)
        self.cleaning_label = QtGui.QLabel(self.segment_tab)
        self.cleaning_label.setTextFormat(QtCore.Qt.RichText)
        self.cleaning_label.setObjectName(_fromUtf8("cleaning_label"))
        self.verticalLayout_7.addWidget(self.cleaning_label)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.max_merging_distance_label = QtGui.QLabel(self.segment_tab)
        self.max_merging_distance_label.setObjectName(_fromUtf8("max_merging_distance_label"))
        self.gridLayout.addWidget(self.max_merging_distance_label, 2, 0, 1, 1)
        self.max_angle_variation_mean_label = QtGui.QLabel(self.segment_tab)
        self.max_angle_variation_mean_label.setObjectName(_fromUtf8("max_angle_variation_mean_label"))
        self.gridLayout.addWidget(self.max_angle_variation_mean_label, 0, 0, 1, 1)
        self.max_merging_angle_label = QtGui.QLabel(self.segment_tab)
        self.max_merging_angle_label.setObjectName(_fromUtf8("max_merging_angle_label"))
        self.gridLayout.addWidget(self.max_merging_angle_label, 1, 0, 1, 1)
        self.max_angle_variation_mean_value = QtGui.QSpinBox(self.segment_tab)
        self.max_angle_variation_mean_value.setMaximum(90)
        self.max_angle_variation_mean_value.setSingleStep(5)
        self.max_angle_variation_mean_value.setProperty("value", 20)
        self.max_angle_variation_mean_value.setObjectName(_fromUtf8("max_angle_variation_mean_value"))
        self.gridLayout.addWidget(self.max_angle_variation_mean_value, 0, 1, 1, 1)
        self.max_merging_angle_value = QtGui.QSpinBox(self.segment_tab)
        self.max_merging_angle_value.setMaximum(90)
        self.max_merging_angle_value.setSingleStep(5)
        self.max_merging_angle_value.setProperty("value", 10)
        self.max_merging_angle_value.setObjectName(_fromUtf8("max_merging_angle_value"))
        self.gridLayout.addWidget(self.max_merging_angle_value, 1, 1, 1, 1)
        self.max_merging_distance_value = QtGui.QSpinBox(self.segment_tab)
        self.max_merging_distance_value.setMaximum(500)
        self.max_merging_distance_value.setSingleStep(10)
        self.max_merging_distance_value.setProperty("value", 10)
        self.max_merging_distance_value.setObjectName(_fromUtf8("max_merging_distance_value"))
        self.gridLayout.addWidget(self.max_merging_distance_value, 2, 1, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout)
        spacerItem2 = QtGui.QSpacerItem(20, 41, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem2)
        self.tab_widget.addTab(self.segment_tab, _fromUtf8(""))
        self.module_tab = QtGui.QWidget()
        self.module_tab.setObjectName(_fromUtf8("module_tab"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.module_tab)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.filter_label = QtGui.QLabel(self.module_tab)
        self.filter_label.setTextFormat(QtCore.Qt.RichText)
        self.filter_label.setObjectName(_fromUtf8("filter_label"))
        self.verticalLayout_8.addWidget(self.filter_label)
        self.module_filter_layout = QtGui.QGridLayout()
        self.module_filter_layout.setContentsMargins(-1, 0, -1, -1)
        self.module_filter_layout.setObjectName(_fromUtf8("module_filter_layout"))
        self.ratio_max_deviation_label = QtGui.QLabel(self.module_tab)
        self.ratio_max_deviation_label.setObjectName(_fromUtf8("ratio_max_deviation_label"))
        self.module_filter_layout.addWidget(self.ratio_max_deviation_label, 0, 0, 1, 1)
        self.ratio_max_deviation_value = QtGui.QDoubleSpinBox(self.module_tab)
        self.ratio_max_deviation_value.setMaximum(10.0)
        self.ratio_max_deviation_value.setSingleStep(0.1)
        self.ratio_max_deviation_value.setProperty("value", 0.3)
        self.ratio_max_deviation_value.setObjectName(_fromUtf8("ratio_max_deviation_value"))
        self.module_filter_layout.addWidget(self.ratio_max_deviation_value, 0, 1, 1, 1)
        self.min_area_label = QtGui.QLabel(self.module_tab)
        self.min_area_label.setObjectName(_fromUtf8("min_area_label"))
        self.module_filter_layout.addWidget(self.min_area_label, 1, 0, 1, 1)
        self.min_area_value = QtGui.QSpinBox(self.module_tab)
        self.min_area_value.setMaximum(1000000)
        self.min_area_value.setSingleStep(100)
        self.min_area_value.setProperty("value", 800)
        self.min_area_value.setObjectName(_fromUtf8("min_area_value"))
        self.module_filter_layout.addWidget(self.min_area_value, 1, 1, 1, 1)
        self.verticalLayout_8.addLayout(self.module_filter_layout)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem3)
        self.tab_widget.addTab(self.module_tab, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.tab_widget)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.play_stop_panel = QtGui.QVBoxLayout()
        self.play_stop_panel.setContentsMargins(-1, 0, -1, 0)
        self.play_stop_panel.setObjectName(_fromUtf8("play_stop_panel"))
        self.play_stop_buttons_panel = QtGui.QHBoxLayout()
        self.play_stop_buttons_panel.setContentsMargins(-1, 0, -1, 0)
        self.play_stop_buttons_panel.setObjectName(_fromUtf8("play_stop_buttons_panel"))
        self.play_video_button = QtGui.QPushButton(self.control_panel)
        self.play_video_button.setCheckable(False)
        self.play_video_button.setObjectName(_fromUtf8("play_video_button"))
        self.play_stop_buttons_panel.addWidget(self.play_video_button)
        self.pause_video_button = QtGui.QPushButton(self.control_panel)
        self.pause_video_button.setEnabled(False)
        self.pause_video_button.setCheckable(False)
        self.pause_video_button.setObjectName(_fromUtf8("pause_video_button"))
        self.play_stop_buttons_panel.addWidget(self.pause_video_button)
        self.stop_video_button = QtGui.QPushButton(self.control_panel)
        self.stop_video_button.setEnabled(False)
        self.stop_video_button.setCheckable(False)
        self.stop_video_button.setChecked(False)
        self.stop_video_button.setObjectName(_fromUtf8("stop_video_button"))
        self.play_stop_buttons_panel.addWidget(self.stop_video_button)
        self.play_stop_panel.addLayout(self.play_stop_buttons_panel)
        self.reset_button = QtGui.QPushButton(self.control_panel)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.reset_button.setFont(font)
        self.reset_button.setAutoFillBackground(False)
        self.reset_button.setAutoDefault(False)
        self.reset_button.setDefault(False)
        self.reset_button.setFlat(False)
        self.reset_button.setObjectName(_fromUtf8("reset_button"))
        self.play_stop_panel.addWidget(self.reset_button)
        self.verticalLayout_2.addLayout(self.play_stop_panel)
        self.horizontalLayout_2.addWidget(self.control_panel, QtCore.Qt.AlignTop)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        self.tab_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Thermography", None))
        self.video_view.setText(_translate("MainWindow", "Input Image", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.input_image_tab), _translate("MainWindow", "Input image", None))
        self.canny_edges_view.setText(_translate("MainWindow", "Edges Image", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.canny_edges_tab), _translate("MainWindow", "Edges image", None))
        self.segment_image_view.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Segment Image</p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.segment_image_tab), _translate("MainWindow", "Segment image", None))
        self.module_image_view.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Module Image</p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.module_image_tab), _translate("MainWindow", "Module image", None))
        self.global_progress_bar.setFormat(_translate("MainWindow", "%p%", None))
        self.from_video_index_label.setText(_translate("MainWindow", "From:", None))
        self.to_video_index_label.setText(_translate("MainWindow", "To:", None))
        self.load_video_button.setText(_translate("MainWindow", "Choose Video", None))
        self.image_scaling_label.setText(_translate("MainWindow", "Input image scaling : 1.00", None))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.video_tab), _translate("MainWindow", "Video Loader", None))
        self.preprocessing_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Preprocessing</span></p></body></html>", None))
        self.undistort_image_box.setText(_translate("MainWindow", "undistort image", None))
        self.angle_label.setText(_translate("MainWindow", "angle:", None))
        self.blur_label.setText(_translate("MainWindow", "blur:", None))
        self.canny_parameters_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Canny</span></p></body></html>", None))
        self.histeresis_label.setText(_translate("MainWindow", "<html><head/><body><p>Histeresis:</p></body></html>", None))
        self.label_max_histeresis.setText(_translate("MainWindow", "max", None))
        self.label_min_histeresis.setText(_translate("MainWindow", "min", None))
        self.dilation_label.setText(_translate("MainWindow", "dilation steps: ", None))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.preprocessing_tab), _translate("MainWindow", "Preprocessing", None))
        self.segment_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Detection</span></p></body></html>", None))
        self.max_gap_label.setText(_translate("MainWindow", "max gap", None))
        self.delta_rho_label.setText(_translate("MainWindow", "delta rho", None))
        self.min_votes_label.setText(_translate("MainWindow", "min votes", None))
        self.min_length_label.setText(_translate("MainWindow", "min length", None))
        self.delta_theta_label.setText(_translate("MainWindow", "delta theta", None))
        self.extend_segments_label.setText(_translate("MainWindow", "extend segments", None))
        self.clustering_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Clustering</span></p></body></html>", None))
        self.num_init_label.setText(_translate("MainWindow", "num init", None))
        self.cluster_type_label.setText(_translate("MainWindow", "type", None))
        self.num_clusters_label.setText(_translate("MainWindow", "num clusters", None))
        self.gmm_value.setText(_translate("MainWindow", "GMM", None))
        self.knn_value.setText(_translate("MainWindow", "KNN", None))
        self.features_label.setText(_translate("MainWindow", "Features:", None))
        self.swipe_clusters_value.setText(_translate("MainWindow", "swipe", None))
        self.use_angle_value.setText(_translate("MainWindow", "angles", None))
        self.use_centers_value.setText(_translate("MainWindow", "centers", None))
        self.cleaning_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Cleaning</span></p></body></html>", None))
        self.max_merging_distance_label.setText(_translate("MainWindow", "max merging distance", None))
        self.max_angle_variation_mean_label.setText(_translate("MainWindow", "max angle variation", None))
        self.max_merging_angle_label.setText(_translate("MainWindow", "max merging angle", None))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.segment_tab), _translate("MainWindow", "Segments", None))
        self.filter_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Filter</span></p></body></html>", None))
        self.ratio_max_deviation_label.setText(_translate("MainWindow", "ratio max deviation", None))
        self.min_area_label.setText(_translate("MainWindow", "min area", None))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.module_tab), _translate("MainWindow", "Modules", None))
        self.play_video_button.setText(_translate("MainWindow", "Play", None))
        self.pause_video_button.setText(_translate("MainWindow", "Pause", None))
        self.stop_video_button.setText(_translate("MainWindow", "Stop", None))
        self.reset_button.setText(_translate("MainWindow", "Reset", None))

